### ISSUE TITLE
cif_core: change data name references in the _refine_ls.number_reflns_gt description

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#102]
Currently, the `_refine_ls.number_reflns_gt` data item description references the `_refine.ls_d_res_high` and `_refine.ls_d_res_low` data items. I propose the following change:

| Old reference | New reference |
|-|-|
| _refine.ls_d_res_high | _refine_ls.d_res_high |
| _refine.ls_d_res_low | _refine_ls.d_res_low |

The proposed new names are already defined in the dictionary as aliases for the given data items. However, implementing the change would make it clearer that the described data item and the referenced data items belong to the same category (**REFINE_LS**).

**Comment by jamesrhester** [comment]
I agree with this change. I assume that the `refine.ls...` forms refer to the mmCIF equivalents.

**Comment by vaitkus** [comment]
Issue has been solved with pull #113.
