### ISSUE TITLE
cif_core: the description of the _diffrn_radiation_wavelength.determination seems to be incorrect

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#105]
The description of the ``_diffrn_radiation_wavelength.determination`` data item seems to be incorrectly copied from the ``_diffrn_radiation_wavelength.details`` data item and is self-referential:

```
Information about the determination of the radiation
wavelength that is not conveyed completely by an
enumerated value of _diffrn_radiation_wavelength.determination.
```

The DDL1 definition was as follows:
```
The method of determination of incident wavelength.
```

**Comment by jamesrhester** [comment]
Will be fixed in next commit

**Comment by vaitkus** [comment]
Great, thank You.

Closing.
