### ISSUE TITLE
ddl.dic: update the type description of 'Complex' and 'Imag' to match that of the related dREL

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#106]
The ``Complex`` type in the DDL is described as "complex number <R>+j\<I\>". On the other hand, dREL uses the 'j' letter as a postfix of the imaginary part rather than the prefix:
1. From the dREL [specification draft](https://www.iucr.org/__data/assets/pdf_file/0007/16378/dREL_spec_aug08.pdf), 2008, section 2.4.2.1:
```
The syntax of a complex number is: ((Real|DecimalInteger)[+-])?(Real|DecimalInteger)[jJ]
An example complex number is:-7893.8221+54.924j
```
2. From the [annotated dREL grammar](https://github.com/COMCIFS/dREL/blob/master/annotated-grammar.rst):
```
imaginary = (real | INTEGER) ("j"|"J")
```

Since DDLm dictionaries are intended to be used with dREL and dREL might even rely on certain data items when resolving the data type (i.e. ``_type.contents``, ``_type.container``, ``_type.purpose``, etc.) it would be worthwhile unifying the notation for both the "Complex" and the "Imag" type.

**Comment by jamesrhester** [comment]
Good catch, and I'm glad somebody is reading the annotated dREL grammar.  As it was based on the dREL publication, it is not surprising that it agrees.

I have proposed removing all references to the format of values in DDLm, so, for example, hexadecimal, octal and binary would all disappear, as these are just alternate ways of representing integers. Likewise, 'Complex' should be simply 'a complex number', with no specification of its representation. That way DDLm can be applied to data expressed in any format.

I will remove the format-specific descriptions in the next commit.

**Comment by jamesrhester** [comment]
I will also remove the various ways of representing integers, as the DDLm group approved that quite a while ago now.

**Comment by jamesrhester** [comment]
Latest update contains these changes.
