### ISSUE TITLE
cif_core: description of the _atom_type_scat.versus_stol_list

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#109]
The ``_atom_type_scat.versus_stol_list`` data item is described in the ``cif_core`` dictionary as:
```
List of scattering factors as a function of sin theta on lambda.
List has the form ['<stol value>':'<scatfac>', ....] in increments of 0.01, increasing from 0.0.
```

However, the sentence describing the list form is a bit misleading since the usage of colons and comma
is not correspond to the CIF2 syntax. It would better be rewritten as:
```
... the form [ [  stol_value_1 scatfac_1 ] [  stol_value_2 scatfac_2 ]... ] ...
```

Disregard this comment if the description is specifically crafted in this way to showcases the applicability of DDLm to other data formats. However, having a CIF2 syntax compliant _description_example.case for this particular data item would be extremely useful.

**Comment by jamesrhester** [comment]
I will edit the description to give the DDLm-style construction. This dataname appears never to have been used and is not used in dREL either, which uses coefficients to calculate.

**Comment by vaitkus** [comment]
Just as a general comment, the data name does seems to be used, however, very sparsely. In the entirety of the COD the data name appears 25 times and in most cases seems to be output by the same program (Jana2000). Since the files were produced prior to introduction of DDLm or CIF2 the values themselves are stored as a structured text field so converting them to an explicitly structured form should not pose any problems. An example of such a file can be found at http://www.crystallography.net/cod/2107628.cif.

**Comment by jamesrhester** [comment]
Thanks for the information.  The latest update contains the fix.

**Comment by vaitkus** [comment]
Great, thank You.
