### ISSUE TITLE
cif_core.dic: the definition of the _exptl_crystal.F_000 contradicts itself

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#110]
The text description of the ``_exptl_crystal.F_000`` states that the data item can have negative values when neutron radiation is used, however, the declared enumeration range (0.0:) disallows that. Maybe the drel definition method should be modified to reflect that or the data item itself could be split into several separate data items?

The addition of the enumeration range to the ``_exptl_crystal.F_000`` data item is also discussed in issue #68.

**Comment by jamesrhester** [comment]
Yes, an interesting one.  The enumeration should be removed, and in future a 'validation' dREL method could be provided to check that this is positive if X-rays are used.  I will remove it in the next commit.

**Comment by jamesrhester** [comment]
See latest commit
