### ISSUE TITLE
cif_core: change the content type of the _audit.creation_date from 'Date' to 'Datetime'

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#115]
The `_audit.creation_date` is currently defined as being of the `Date` content type which allows recording the date in the YYYY-DD-MM format. However, about 10000 entries in the COD record a full datetime using this item (i.e. 2009-06-17T16:02:59-00:00). The number of affected entries is not great, however, it demonstrates the intention or at least a trend to use the `_audit.creation_date` in a slightly different way. As such I propose to redefine the `_audit.creation_date` data item as being of the `Datetime` type. Since the `Date` values are a subset of the `Datetime` values, switching the type should generally not break any compatibility as the YYYY-DD-MM values would still be treated as valid ones.

Alternatively, maybe a `_audit.creation_datetime` data item could be created to store such values?

**Comment by jamesrhester** [comment]
I agree that the type can simply be changed to DateTime

**Comment by vaitkus** [comment]
Change implemented in PR #118.
