### ISSUE TITLE
ddl: interaction between standard uncertainties and enumeration ranges

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#116]
Several data item definitions in the `core.dic` dictionary (`_atom_site.occupancy`, `_refine_ls.abs_structure_Flack`, `_refine_ls.abs_structure_Rogers`) explicitly describe how the standard uncertainty values interact with the range values. For example, the definition of the `_atom_site.occupancy` data item states:
```
The value must lie in the 99.97% Gaussian confidence interval -3u =< x =< 1 + 3u.
The _enumeration.range of 0.0:1.0 is thus correctly interpreted as meaning
(0.0 - 3u) =< x =< (1.0 + 3u).
```

The same [min_range - 3u; max_range + 3u] approach is applied to other mentioned items.

I was wondering if the same approach should be applied to other measurand (s.u. bearing) data items that are restricted to a certain range (i.e. `_cell.length_a`). If so, maybe it is worth including this piece of information in the definition of the _enumeration.range data item from the `ddl.dic` dicationary?

**Comment by jamesrhester** [comment]
Sounds like a good idea. I'll run it by the DDLm group.

**Comment by jamesrhester** [comment]
The DDLm group had no comment, therefore this proposal is accepted.

**Comment by vaitkus** [comment]
> The DDLm group had no comment, therefore this proposal is accepted.

It seems that several hours after this post there were some objections raised in the ddlm-group. Is this proposal still treated as accepted?

**Comment by jamesrhester** [comment]
Indeed there were some objections so it is not yet accepted.

**Comment by jamesrhester** [comment]
Following comments in the DDLm group that there was no unambiguous way to specify actual limits in the presence of SUs, the following text was proposed with no immediate objections:
 
> The inclusive range of values "from:to" allowed for the defined item. If items have associated SU, the reported value may fall outside these limits.

This alerts those wishing to base validation on the range limits that they will need to adopt some particular policy when checking these ranges in the presence of SU, but does not prescribe that policy.

**Comment by jamesrhester** [comment]
e00774a contains this update to the ``_enumeration.range`` definition. I have left the original definitions that raised this issue unchanged, on the assumption that they provide more detailed (but not machine-readable) information about how to check the range more precisely.
