### ISSUE TITLE
ddl: introduce an explicit uniqueness constraint

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#119]
### Problem
Currently, DDLm offers several ways of declaring looped values as being unique:

- Artificial primary key ( 'Key' type purpose );
- Simple primary key (_category.key_id data item);
- Composite primary key (_category_key.name).

However, all of these approaches are insufficient in cases when there exists several candidate keys in the same loop. I propose to introduce an additional way of expressing mandatory uniqueness in a formal way.

### Proposal

The uniqueness constraint would be:
1) Completely optional,
2) Provided in the category definition;
3) Applicable to both single data items and groups of data items.

Possible implementation:
```
loop_
_unique_constraint.id
_unique_constraint.data_names
1 [  _category_data_item_1 ]
2 [  _category_data_item_2 _category_data_item_4 ]
...
```

Or even in a more generalised fashion that would allow to introduce additional types of constraints in the future:
```
loop_
_constraint.id
_constraint.type
_constraint.data_names
1 Unique [  _category_data_item_1 ]
2 Unique [  _category_data_item_2 _category_data_item_4 ]
3 Mandatory [  _category_data_item_1 _category_data_item_2 ]
...
```

### Examples of practical application

The ``SPACE_GROUP_SYMOP`` category in the ``CIF_CORE`` dictionary references the ``_space_group_symop.id`` both using the ``_category.key_id`` and the ``_category_key.name`` data items. The same category also contains the ``_space_group_symop.operation_xyz`` data item which should be unique, however, this constraint is not formally expressed in any way.

Is it worthwhile to develop this approach any further, i.e. create the prototype data item definitions?

**Comment by jamesrhester** [comment]
Thank you for taking the time to prepare a detailed proposal. However, as I commented in #120, uniqueness of individual dataname values may be removed by extension dictionaries.  Also, such checks can also be encoded using a validation dictionary. For example, in this case you could imagine the following definition (off the top of my head, may have some slightly incorrect tags and syntax):

```
save_check_symop.uniqueness
_definition.id _check_symop.uniqueness
_name.category_id check_symop
_name.object_id     uniqueness
_description.text
;
      Check whether or not the list of symmetry operations in the data file
      are all unique.
;
loop_
  _enumeration_set.state
  _enumeration_set.detail
True                    'All symmetry operations are unique'
False                  'At least one symmetry operation is repeated'

loop_
_method.purpose
_method.expression
Evaluation
;
already_seen = []
_check_symop.uniqueness = 'True'
loop q as space_group_symop {
    if(q.operation_xyz in already_seen) {
       _check_symop.uniqueness = 'False'
      break }
    else {
        already_seen ++= q.operation_xyz
   }
}
;
```
If necessary, the loop could be moved to a dREL dictionary function and that function called, to save repetition.  The information in the definition can be used to construct checking routines and their output messages, and the check is documented and usable. I have a vision of CheckCIF eventually moving to this way of operation, rather than the checks being performed out of sight.

Note that there is a fairly well-tested [EBNF for dREL available](https://github.com/COMCIFS/dREL/blob/master/annotated-grammar.rst) if anyone feels inclined to e.g. produce a Perl dREL interpreter.

**Comment by vaitkus** [comment]
I understand that extension dictionaries might need to drop the uniqueness constraint in some instances like the one described in answer to #120 (`_refln.[h,k,l]`). However, that specific case should probably not cause the removal of a formal uniqueness constraint all together. Ontologies are bound to evolve and since *removal* of a constraint does not carry the risk of making the existing data invalid it can easily occur on the case-by-case basis.  

Alternatively, the constraint could be dynamically removed by specific extending dictionaries. This could be achieved, for example, by redefining the category in question in the extending dictionary (i.e. the twinning dictionary could redefine the REFL category and **not** overwrite it during the import of the core dictionary). This approach seems quite similar in spirit to the proposed dREL one: CIF files created in regards to the core dictionary would be required to return TRUE while the check could be ignored altogether when the extension dictionaries are involved. However, the algorithmic nature of the dREL-based approach introduces addictional complexity of analysing the dREL methods (a task that is indeed made much easier by the EBNF grammar).

I do not argue against the great potential of dREL methods to express and codify constraints. Even if one does not produce a full-fledged dREL interpreter, the code itself can be used as pseudo-code description of complex validation tasks that can be implemented using the language of choice. However, for well known specific constraints such as the uniqueness one, this seems like a bit redundant.

I understand that COMCIFS has its own vision for DDLm dictionaries and that my mindset is somewhat stuck with the ideas of the relational model. However, the need to automatically relate abstract data ontologies to the relational model seems to be common one and well known ontology languages such as OWL do have the means to express the 'UNIQUE' and 'NOT NULL' constraints in a simple machine readable way ([10.1016/j.aci.2017.07.003](https://doi.org/10.1016/j.aci.2017.07.003)). Wouldn't it be useful to have something similar in DDLm?

**Comment by jamesrhester** [comment]
It is true that, just as importing dictionaries can extend the category key loop, it would also be possible for the importing dictionary to remove a uniqueness constraint.  However, this makes me nervous as software authors are prone to hard-code information that they find in a dictionary, and so, while a future importing dictionary may remove the uniqueness constraint, there is no guarantee that software will automatically adjust to this. For this reason the <code>_audit.schema</code> tag was introduced to flag to software that something has changed.

In any case, I'll run this by the DDLm group to see what others think.

**Comment by jamesrhester** [comment]
Just noting here that the DDLm group discussion was inconclusive, and so no change will be made at this time. I will close this issue now but not that it can be opened again if the situation changes in the future and a need for uniqueness constraints is identified.

**Comment by jamesrhester** [comment]
Just noting here that the DDLm group discussion was inconclusive, and so no change will be made at this time. I will close this issue now but not that it can be opened again if the situation changes in the future and a need for uniqueness constraints is identified.
