### ISSUE TITLE
cif_core: uniqueness of the _space_group_symop.operation_xyz data item is not required in any way

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#120]
The ``_space_group_symop.operation_xyz`` provides the list of symmetry operators in a space group and as such should logically contain unique values. However, currently, this is not expressed formally in any way.

A quick fix for this issue would be to declare in the ``SPACE_GROUP_SYMOP`` category using the ``_category_key.name`` data item.

A more complex and generalised approach is described in issue #119.

**Comment by jamesrhester** [comment]
This unfortunately a legacy issue. You will see in the core dictionary a dREL definition for `_space_group_symop.id` that creates the category key value from the sequence number of the symop. This id is then used to refer to the symops in symmetry codes.  This way of fixing an absent key goes against the fundamental relational concept that the non-key datanames are functions of the key datanames (in this case, an assumed one-to-one mapping saves the day).

Clearly the original CIF should have had `_space_group_symop_id` as a required item. This problem arises also for `_refln.[h,k,l]` which together form the key of the REFLN category.  This is fine until a reflection is measured twice or reflections from twinned crystals should be listed together. With our better understanding 20 years down the track we understand that an opaque key is the best choice for extensibility. 

So I would be against making any changes to DDLm to accommodate this historical accident.  The best way to treat this would be to define a "check" dataname in a validation dictionary with a dREL method to carry out the check.
