### ISSUE TITLE
cif_core: items linked in a circular fashion

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#124]
Several items in the ``CIF_CORE`` dictionary link to each other using the ``_name.linked_item_id`` item. What is more, one of the item in the pair consistently has the 'Encode' purpose which does not allow the definition to contain the ``_name.linked_item_id`` data item. Occurrences:

1. ``_diffrn_scale_group.code`` (Encode) and  ``_diffrn_refln.scale_group_code`` (Link);
2. ``_diffrn_standard_refln.code`` (Encode) and ``_diffrn_refln.standard_code`` (Link).

Is this done purposely? Normally, I would expect one of the items to be assigned the ``Encode`` purpose and contain no links while the other would be assigned the ``Link`` purpose and link to the first item via ``_name.linked_item_id``.

Can the ``_name.linked_item_id`` item be removed from the definitions of the ``_diffrn_scale_group.code`` and ``_diffrn_standard_refln.code`` items?

**Comment by jamesrhester** [comment]
Yes, I have also noted this circularity recently while working with cif_core but have not yet committed my changes. These items should not be linked in a circular fashion. The primary items are `_diffrn_scale_group.code` and `_diffrn_standard_refln.code`, as you have determined.  `_name.linked_item_id` should be removed from these definitions.
