### ISSUE TITLE
ddl: slight clarification on file import restrictions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#128]
The current definition of the ``_import_details.mode`` states that:
```
     Code identifying how the definition referenced
     by _import_details.frame_id is to be imported.

     "Full" imports the entire definition together with any child
     definitions (in the case of categories) found in the target
     dictionary. The importing definition becomes the parent
     of the imported definition. As a special case, a 'Head' category
     importing a 'Head' category is equivalent to importing all children
     of the imported 'Head' category as children of the importing 'Head'
     category. A non-'Head' category may not import a 'Head' category
     in "Full" mode.
     
     "Contents" imports only the attributes found in the imported
     definition.
```

I propose to slightly modify the description in the following ways:

1. **Clearly state that the 'Full' import can only appear in a category context.**
This is implied  by the fact that an Item cannot become a parent of another Item or let alone a Category. Or maybe there are some usage patterns that I am not aware of?
2. **Clearly state that a 'Head' category can only be imported in 'Full' mode and only by another 'Head' category.** The current definition does a good job of explaining how the 'Head' import should be treated, however, it does not disallow the import of a 'Head' category under the 'Contents' mode. This is probably not desirable, since the dictionary might end up with two head categories.

The updated definition could be reworded in a similar fashion:
```
     Code identifying how the definition referenced
     by _import_details.frame_id is to be imported.

     "Full" imports the entire definition together with any child
     definitions (in the case of categories) found in the target
     dictionary. The importing definition becomes the parent
     of the imported definition. As such, the "Full" mode must
     only be used in category definitions. 

     As a special case, a 'Head' category importing a 'Head'
     category is equivalent to importing all children of the imported
     'Head' category as children of the importing 'Head' category.
     A 'Head' category can only be imported in "Full" mode and only
     by another 'Head' category.
     
     "Contents" imports only the attributes found in the imported
     definition.
```
Or is it too limiting in some sense?

**Comment by jamesrhester** [comment]
Your enhanced definition is consistent with the intention of the import mechanism and is not too limiting.  Indeed it saves programmers time trying to support situations that never arise.
