### ISSUE TITLE
Isolated function calls in dREL

### ISSUE THREAD

**Issue by merkys** [COMCIFS/cif_core#132]
In COMCIFS/dREL#2 it has been decided to disallow isolated dREL function calls (i.e. without left-hand sides in assignments). CIF_CORE [still contains such constructs](https://github.com/COMCIFS/cif_core/blob/fe4e9861bb5d276373fe244e582860d51c1efbba/ddl.dic#L1382).

**Comment by jamesrhester** [comment]
The identified call has been fixed in 8ca3b54. Validation dREL containing undefined 'throw' and 'alert' statements has also been removed from ``_space_group.crystal_system``, as best put into an explicit validation dictionary.
