### ISSUE TITLE
ddl.dic: improper URI in '_dictionary.uri'

### ISSUE THREAD

**Issue by merkys** [COMCIFS/cif_core#136]
`ddl.dic` gives the following value for `_dictionary.uri` data item:
https://github.com/COMCIFS/cif_core/blob/b60d37a506e16d67d321e81d9034e8a077715134/ddl.dic#L14
While this URI resolves to the GitHub preview of the dictionary file, downloading it and passing to the parser leads to syntax error, as instead of a CIF, the URI resolves to an HTML page (of the CIF).

I believe this is unintended: I expect the `_dictionary.uri` point to a CIF, which could be readily downloaded, parsed and used. I suggest for time being to replace the contents of `_dictionary.uri` with `https://raw.githubusercontent.com/COMCIFS/cif_core/cif2-conversion/ddl.dic`, which resolves to a CIF file of the dictionary.

**Comment by jamesrhester** [comment]
Agreed.

**Comment by jamesrhester** [comment]
Merged pull request from @vaitkus

**Comment by merkys** [comment]
> Merged pull request from @vaitkus

Are you referring to #137? That PR fixed the `_dictionary.uri` for `cif_core.dic`, not `ddl.dic`. I will open a separate PR for this issue.
