### ISSUE TITLE
ddl.dic (cif2-conversion): _dictionary_valid.application _method.purpose attribute has wrong value

### ISSUE THREAD

**Issue by kkitahara5101** [COMCIFS/cif_core#138]
Hello.
I recently started reading latest CIF dictionaries, and I found a tiny (?) issue.

Currently, ['Definition' is assigned to '_method.purpose' attribute of '_dictionary_valid.application'](https://github.com/COMCIFS/cif_core/blob/cif2-conversion/ddl.dic#L872).
However, the corresponding method does not evaluate any attribute of '_dictionary_valid.application' but the value of '_dictionary_valid.application'.
Should it be 'Evaluation'?

**Comment by jamesrhester** [comment]
Yes, this should be 'Evaluation' as it evaluates the value of the defined data name.

**Comment by jamesrhester** [comment]
Pull request #147 fixes this.
