### ISSUE TITLE
ddl.dic (cif2-conversion), _type.contents: are 'Count' and 'Index' necessary?

### ISSUE THREAD

**Issue by kkitahara5101** [COMCIFS/cif_core#140]
The only difference between 'Count', 'Index' and 'Integer' is the allowed enumeration range. Since _enumeration.range attribute is explicitly given for the (allmost?) all items with _type.contents of Count or Index in the current dictionaries, the above difference is not significant at all. If there are no other reasons to keep 'Count' and 'Index', I would like to suggest to replace them with 'Integer' and remove them from ddl.dic. It will make an implementation simpler a bit.

One possible use case may be to implicate the purpose of the associated item. However, such an implication is failed in some items, e.g. atom_type.electron_count in cif_core, it has 'Index' instead of 'Count'.
https://github.com/COMCIFS/cif_core/blob/4b61be5136fa10c2f0d5a52e45b207181d05fcfd/cif_core.dic#L21464-L21482

**Comment by jamesrhester** [comment]
I agree with @kkitahara5101. I guess the intention was to give some indication of the function of the item but it seems inconsistent. I will just consult with the DDLm group to confirm that there is no issue that they can see.

**Comment by jamesrhester** [comment]
The DDLm group suggests initially deprecating "Count" and "Index". I will raise a new issue that all uses of "Count" and "Index" be changed to "Integer", and to deprecate them in the DDLm file.
