### ISSUE TITLE
Version numbers of dictionaries in developement

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#141]
Even though proper versioning protocol is still under discussion (see #47) I think it would be worthwhile to establish some general rules regarding the way developmental versions of the dictionaries should be treated in the scope of this repository. These rules could later on be integrated into the GitHub [contributing guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) or other documentation for the repo.

To begin with, I am making a few assumptions that I would like to state clearly in case they are wrong and should be corrected:
1. Official IUCr dictionary releases are assigned a stable version number and placed on the IUCr ftp sever/webpage.
2. In contrast, this GitHub repository is used to develop the IUCr dictionaries and as such the same version number might identify several different iterations conceived during the development cycle (i.e. different dictionary commits). As these developmental dictionaries are prone to change, their use in applications should be limited and the official dictionary releases should be preferred.
3. The dictionary version should only be treated as an official one once it is moved (copied) from the GitHub repo and placed on the IUCr resources (website, ftp).

#### Question 1: how often should the version number be changed?
Dictionaries under development often undergo several revisions of various severity before they are prepared for a proper release. The question is, should each of these revisions cause a change of the version number or should they accumulate? Consider the following example:

Dictionary A has the version number **2.6.3**. Over a period of time, a series of changes are applied to the dictionary without issuing an official IUCr release. The changes of the following severity are applied in sequence: **_Minor(m1)-Major(M1)-Bugfix(b1)-Minor(m2)-Bugfix(b2)_**. How should the dictionary A version progress?

**The sequential approach.** Version numbers are incremented the same way they would be incremented when following a stable release schedule:
 `` 2.6.3 -> 2.7.0 (m1) -> 3.0.0 (M1) -> 3.0.1 (b1) -> 3.1.0 (m2) -> 3.1.1 (b2) => officially released as 3.1.1``

**The cumulative approach.** Version number of the greatest severity gobbles up all changes that are of the same severity or greater:
``2.6.3 -> 2.7.0 (m1) -> 3.0.0 (M1) => major change will absorb all other future changes till the release; officially released as 3.0.0 ``

Personally, I would lean towards the **cumulative approach** since it avoids strange version hops in official releases (2.6.3 -> 3.1.1) and as a result avoids transient vanishing versions (3.0.1 was never an official release and as such is not stored in IUCr archives).

#### Question 2: how can the developmental version be distinguished from an official release?
I propose that the developmental version would receive a special version number prefix of postfix, i.e. **pre**-3.5.4, 3.5.4-**dev**, 3.5.4-**wip**, etc.

#### Question 3: who should change the version number?
I propose that the version number of the dictionaries would be controlled explicitly by the maintainer(s) of the repo; version numbers assigned by external sources have to be checked by the maintainer(s) anyway.

#### Question 4: how are stable dictionary versions released?
A stable dictionary version is released by updating the appropriate metadata and distributing the stable version to the official sources (i.e. the IUCr FTP). The metadata that should be updated include the dictionary version (``_dictionary.version``, ``_dictionary_audit.date``), dictionary URI (``_dictionary.uri``), timestamps (``dictionary.date``, ``_dictionary_audit.date``) and the human readable revision history (``_dictionary_audit.revision``).  Update of the version number is normally carried out by removing the developmental version prefix/postfix (i.e. 3.1.5-dev -> 3.1.5). Once assigned, the stable release version number is permanent.

Once the stable release is issued a new developmental version is created from the latest release. The developmental version gets assigned a new version number which differs from the latest one by a bugfix release (i.e. 3.1.5 -> 3.1.6-dev). In addition to that a corresponding ``DICTIONARY_AUDIT`` loop entry is created which will be used to store the dictionary CHANGELOG during the next development cycle.

What do you think?

**Comment by kkitahara5101** [comment]
I have not yet followed the previous discussion. I am sorry for this.
But, I would like to suggest an idea that is somewhat similar to the cumulative approach of @vaitkus.

In my opinion, complete history of the developments does not need to be exposed to users. What users want to know is the changes between the stable releases. Especially, time ordering of the changes is not important for users.

I suggest to have e.g. `DEVELOPMENT` category (or just a comment?) only to log the changes between two stable releases. This category may have `_development.version`, `_development.date`, etc. When new version is released, the changes logged in this category is merged into one entry of `DICTIONARY_AUDIT` category. If the changes include 'major' one, the next release will be a major release, otherwise a minor or a bugfix release depending on the changes included in `DEVELOPMENT` category. In this way, the official and the developmental version can be separated, and the frequency of the change of the official version can be minimized.

**Comment by vaitkus** [comment]
I am glad that we agree on the necessity to explicitly mark the developmental version.

However, I would like to stress the importance of changing the dictionary version number (`_dictionary.version`) _during_ the development process. Since version numbers can be referenced in the import statements of other dictionaries as well as automatically recorded in the CIF files during the validation process, each version number MUST identify a unique dictionary release. Having a developmental version with the same version number as a stable release would go against this.

I do agree that not all changes have to be exposed to the user, especially, since some changes might cancel each other out (i.e. a data item modification followed by a deletion). As such, I have updated the answer to the 4th question to reflect that.

**Comment by kkitahara5101** [comment]
Thanks for the reply @vaitkus.

I do not have enough experience on the import and validation processes, yet. That is why I did not notice the importance of changing _dictionary.version during the development process. Now I understand this.

Then, how about to have 6 version numbers for developments? It works e.g. from official release 1.2.3 as follows:
--(copy to repo.)--> 1.2.4-dev-0.0.0
--(bugfix)--> 1.2.4-dev-0.0.1 (official bugfix version is incremented only ones during development)
--(minor)--> 1.3.0-dev-0.1.0
--(bugfix)--> 1.3.0-dev-0.1.1 (bugfix is absorbed by the previous minor change in official version)
--(minor)--> 1.3.0-dev-0.2.0 (official minor version is incremented only ones during development)
...
----> 2.0.0-dev-4.3.13 --(stable release)--> 2.0.0

**Comment by jamesrhester** [comment]
I agree with @vaitkus' 3 assumptions and proposed version naming strategy, I also prefer "cumulative" versioning.  I don't think there is any need for a development category as proposed by @kkitahara5101, as the Github repository contains all necessary information.  The extra three development version numbers look like a useful idea as well. I think there is no need for the maintainer(s) to allocate these version numbers, instead the pull request can include the updated version and whoever merges the pull request can check and maybe correct versioning as part of the merge.

**Comment by vaitkus** [comment]
The six digit version number proposed by @kkitahara5101 has the benefit of uniquely identifying each developmental iteration, however, the three additional digits might be a slight semantic overkill. I mean, the last three digits represent not only compatibility between the base stable release and the developmental version (i.e. minor between `1.2.3` and `1.2.3-dev-0.1.0`), but also between two developmental versions (i.e. bugfix between `1.2.3-dev-0.1.0` and `1.2.3-dev-0.1.1`). An example of when this versioning scheme breaks can also be produced.

Let's start with a version number `3.0.0-dev-0.0.0`:
1. We apply a minor change (m) by adding a data item `X`; (`3.0.0-dev-0.0.0` -> `3.0.0-dev-0.1.0`);
2. Later on we decide that the item is actually not needed and remove the `X` data item. Such deletion triggers a major (M) change (`3.0.0-dev-0.1.0` -> `3.0.0-dev-1.0.0`);
3. Even later on we find a bug and fix it, thus triggering a bugfix (b) change (`3.0.0-dev-1.0.0` -> `3.0.0-dev-1.0.1`);
3. Then, if we would release the dictionary at step 3), we would end up with a major version release ( `3.0.0-dev-1.0.1` -> `4.0.0`) even though no major changes would be reflected in the dictionary file.

Alternatively, the versioning protocol that I proposed does not prohibit to lower the developmental version in case it is required  (`3.0.1-dev` -> `3.1.0-dev` -> `3.1.0-dev` -> `3.0.1-dev` -> `3.0.1`). This also illustrates the importance of constantly updating the `_dictionary_audit.revision` in order to have immediate access to list of changes to consult when determining the appropriate version change level.

We could also fuse our two approaches to some extent in order to retain the unique addressability of each development iteration. The main difference would be to use a simple integer as a postfix with no additional semantics to denote different dev. version. Let's assume we just released version 3.0.0:

1. `3.0.1-dev.1` -- initial dev copy with no notable changes
2. `3.1.0-dev.2` -- major change
3. `3.1.0-dev.3` -- minor change
4. `3.0.1-dev.4` -- reverse the major change

I prefer to start with 3.0.1 since the version number prior to the -dev postfix usually refers to the version that is _being_ developed and we are sure to get at least a single change of a bugfix level or higher prior to a new release. Of course, explicitly seeing the version that the dev is based on is useful, but the same information can also be acquired from the `DICTIONARY_AUDIT` loop.

@kkitahara5101, please correct me if I misunderstood something.

@jamesrhester, just to clarify, in my answer to Q3 by the term "maintainer(s)" I meant the people who have the permissions to merge PRs. And sure, we can add "updating the version number" to the list of things a contributor should do prior to issuing a PR if this has the chance of reducing the workload of the maintainer(s).

**Comment by kkitahara5101** [comment]
Thanks for the comment @vaitkus.

Additional three-digit scheme is the most verbose choice. And, as pointed out by @vaitkus, it can fail when a change is deleted (I did not notice this case, thanks). I, basically, prefer simpler solution.

**Comment by jamesrhester** [comment]
I think we almost have a consensus on these guidelines:
1. Cumulative approach
2. Add a suffix ``-dev-n`` where n increments with each change
3. Submitter encouraged to change the version number in the PR, otherwise the merger will have to do it
4. As proposed, with the addition that at the point that a version is released we would attach a tag in Git corresponding to the release version. The actual update on the IUCr website may have a delay so this provides a handy record.  We could also merge into a master branch at this point.

So what we now need is to capture the procedure into a document. Would @vaitkus mind producing a concise markdown document within comcifs.github.io for circulation among the good people of core-dmg and ddlm-group?

**Comment by vaitkus** [comment]
The draft version has been prepared here: https://github.com/COMCIFS/comcifs.github.io/blob/dictionary-developement-practices/dictionary_development_practices.md

I hope that my phrasing is legible enough for people who have not participated in this discussion. Feel free to change it to your liking.

**Comment by jamesrhester** [comment]
Looks good, I will pass the link to the discussion groups in case they have a comment.

**Comment by jamesrhester** [comment]
I have now shifted the draft document into the "accepted" directory on comcifs.github.io. I note that I haven't really been following the suggested procedure, as github provides so much version tracking already.  I'll raise an issue for an automated check.
