### ISSUE TITLE
Proposal to include multiple versions of the same dictionary in the repo

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#143]
Currently, the repository only contains the latest (a.k.a. developmental version) of the dictionaries. However, having all of the stable releases alongside the developmental version would be extremely useful.

Potential layout:
```
├── cif_core_dev.dic
├── cif_img_dev.dic
└── dic
    ├── cif_core
    │   ├── cif_core_3.11.10.dic
    │   ├── cif_core_3.11.9.dic
    │   ├── cif_core_3.12.0.dic
    │   ├── cif_core_3.13.0.dic
    │   └── cif_core_3.13.1.dic
    └── cif_img
        ├── cif_core_3.0.2.dic
        └── ...
```

Under the proposed layout each dictionary would have a top-most level developmental version (``cif_core_dev.img``, ``cif_img_dev.img``) and a dedicated subdirectory under ``dic/`` that would store all of the stable versions with the appropriate version number in their name. Since this repository is mainly focused on developing the DDLm-conformant dictionaries only newer, DDLm-compliant versions would be stored here. DDL1 compliant versions could similarly be stored in the 
``DDL1-legacy-dictionaries`` repo.

The IUCr FTP servers would, of course, hold precedence over these repositories.

What do you think?

**Comment by jamesrhester** [comment]
I can see the reason that git tags are insufficient here, as all the dictionaries are contained in a single repository and so a tag cannot apply to a single dictionary.  However, I think it might be better to actually create a separate repository for each dictionary, perhaps in anticipation that more people interested in particular dictionaries will appear and want to work in their own workspace.

Then we can just tag releases appropriately. What I'm not sure about is how easy it is to carry along the relevant git history when a dictionary is moved to a separate repository (not that there is much for the non-core/ddlm dictionaries).

What we should also do is certainly get back to having a "stable" and "development" branch. I think "cif2-development" ready for merging back to "development".

**Comment by jamesrhester** [comment]
Actually I have now merged cif2-conversion into master. I propose that 'master' becomes the default branch and we just create any side branches for larger projects, otherwise we can just merge into master.

**Comment by jamesrhester** [comment]
All dictionaries are now in separate repositories.
