### ISSUE TITLE
cif_img.dic: _array_intensities.pixel_[slow|fast]_bin_size is assigned an incorrect content type

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#153]
The human-readable description of the ``_array_intensities.pixel_slow_bin_size`` and ``_array_intensities.pixel_fast_bin_size`` data items state that the data item should allow floating point values:

```
It is specified as a float to allow for binning algorithms that
create array elements that are not integer multiples of the
detector pixel size.
```

However, the currently assigned ``Count`` content type only allows integer values.

**Comment by vaitkus** [comment]
A possible solution for the issue was proposed in PR #154.

**Comment by jamesrhester** [comment]
The text definition clearly states that this should be a Real number.
