### ISSUE TITLE
Clarification on the 'Loop' definition class needed

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#162]
``DDLm`` defines the eligibility of a data item to appear in a looped list using the ``_definition.class`` category. If the parent category has the ``Set`` class, child data items must not appear in a loop. If the parent category has the ``Loop`` class, child data items **must** appear in a loop:
``
Category of items that in a data file must
reside in a loop-list with a key item defined.
``

However, it seems that in practice (including the dictionaries themselves) the loop is sometimes omitted if a looped item only has one value. For comparison, ``DDL1`` has three 'loopness' states that make a distinction between *being able to* appear in a loop and *having to* appear in a loop (summarised in a table below). 

|  State | Can appear in a loop? | Must appear in a loop? |
| --- | --- | --- |
| ``yes`` |  + | +|
| ``no`` | - | - |
| ``both`` | + | - |

Formal definition of the ``DDLm`` ``Loop`` class implies the ``DDL1``  ``yes`` state while actual usage corresponds to the ``both`` state. Which one of these usages is the intended one? In case it indeed corresponds to the ``both`` one, maybe the definition of the ``Loop`` class could be updated by replacing the word "must" with the word "may" or "should" (as per [RFC 2119](https://tools.ietf.org/html/rfc2119))?

**Comment by jamesrhester** [comment]
With the introduction of CIF2 and DDLm it was recognised that loops with a single row are functionally identical to the same values given as key-value pairs. This has always been the case with DDL2 dictionaries. So the language of the definition should correspond to ``both``. I agree that "must" should be replaced by "may".

**Comment by vaitkus** [comment]
Great , thank you for the clarification.

Possible solution is provided in PR #163.

**Comment by jamesrhester** [comment]
Thank you for the PR.
