### ISSUE TITLE
Angle calculations using Acosd may produce the incorrect quadrant

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#167]
_geom_angle.value dREL suggests that the angle can only ever be between 0 and 180 as this is the range returned by acosd. However, the definition states that -180:180 is the possible range. The value should probably be adjusted to choose the correct quadrant, or the possible range should be adjusted. This type of calculation appears a few times in the cif core dictionary.

```
     With a as geom_angle
     xc = List()
     bundle = [[a.site_symmetry_1,a.atom_site_label_1],
               [a.site_symmetry_2,a.atom_site_label_2],
               [a.site_symmetry_3.a.atom_site_label_3]]
     for symop,label in bundle {
         xf   =   SymEquiv(symop,  _atom_site[label].fract_xyz)
         xc ++=  _atom_sites_Cartn_transform.matrix * xf
     }
       v1,v2  =  xc[0]-xc[1], xc[2]-xc[1]
 
      _geom_angle.value =  Acosd ( v1 * v2 / ( Norm (v1) * Norm (v2) ) )
```

**Comment by jamesrhester** [comment]
``_geom_angle.value`` does not seem to appear in the COD so we could restrict it to 0:180. However, as -180:0 is not strictly incorrect we can leave the range as is, but dREL will never produce the negative angles.

**Comment by vaitkus** [comment]
I just wanted to note that the `_geom_angle.value` data item does appear in the COD quite often using the now aliased data name `_geom_angle`. I assume that the same dREL applies to the item regardless which of the names is used?

About 84% of entries (380354 entries) in COD revision 249255 contain the `_geom_angle` data item. Out of those **none** contain a negative numeric value and about **3** entries contain proper numeric values above 180. Based on this, changing the range to [0.0; 180.0] is a great idea that is also backed-up by actual data in the wild. Leaving the range as  [-180.0; 180.0], on the other hand, would actually introduce some ambiguities regarding the situations in which the negative values should actually be used.

I have not yet run similar test on the `_geom_hbond.angle_DHA` data item, but I image that it would yield most similar results, and as such, the range for this item should also be changed from [-180.0; 180.0] to [0.0; 180.0].

As a side note, addition of the [-180.0; 180.0] range for the torsion angle (`_geom_torsion.angle` data item) works great both with the human-readable description and the data already out there in the wild.

**Comment by jamesrhester** [comment]
In light of this comment I think we can comfortably change the ranges for _geom_angle. Yes, the same dREL applies.

**Comment by jamesrhester** [comment]
aefcf14 contains this update.
