### ISSUE TITLE
Provide an example of the use of the database_related category

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#169]
#76 added a new category but no example is given.

**Comment by vaitkus** [comment]
I tried to come up with an example, but got a bit confused by the states of `_database_related.relation`.

It is quite easy to come up with an example that links `Identical` crystal structures in the COD and CSD, however, I am not sure about the other states. For example, what relation should be used to link a crystal structure of caffeine to an entry in CAS (code 58-08-2)?

**Comment by jamesrhester** [comment]
If you find relations that you think are useful but not captured by the current list feel free to invent another relation and add it in, for example, the entries refer to the same "material". There is no need to find an example for all of the listed relations, that might be a bit challenging.

**Comment by vaitkus** [comment]
For now, I opted to add the `Other` relation type (in PR #353). In the future if the category is widely used, the special details field could be analysed to identify the most relevant additional relation types.

**Comment by vaitkus** [comment]
Resolved by merging PR #353.
