### ISSUE TITLE
The _refln.form_factor_table table data item contains dimension

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#171]
The `_refln.form_factor_table` is of the `Table` content type and contains the `_type.dimension` data item in its definition. According to the definition of the `Dimension` data type it should only be applied to Lists, Arrays and Matrices. Does the dimension data item serve any purpose in this case or could it be removed?

**Comment by jamesrhester** [comment]
Well spotted, it serves no purpose and can be removed.

**Comment by vaitkus** [comment]
Issue is addressed with PR #225.
