### ISSUE TITLE
DDLm definition of the _exptl_crystal.colour data item is not compatible with the DDL1 definition

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#189]
The  `_exptl_crystal.colour` data item in the `DDLm` version of the `CIF_CORE` dictionary is defined as a list of 3 elements ([`_exptl_crystal_appearance.general`, `_exptl_crystal_appearance.intensity`, `_exptl_crystal_appearance.hue`]) while the `DDL1` version of the  `CIF_CORE` dictionary defines it as a simple concatenated text string without a container. Since neither `CIF_1.1` nor `DDL1` support lists or other container types, CIF files that contain the `_exptl_crystal.colour` data item simply cannot be simultaneously valid according to both  the `DDL1` and the `DDLm`.  It should be noted that the  `_exptl_crystal_colour` (`_exptl_crystal.colour`) data item has been widely used and appears in at least ~78% of the COD entries (r249495, ~450 000 total entries).

As discussed in PR #188, one possible solution could be to revert the `_exptl_crystal.colour` data type back to the original DDL1 type (text string with no container) and define an entirely new data item for the structured (list) values.

**Comment by jamesrhester** [comment]
This is indeed a serious problem. We must fulfill our promise that no changes are made compared to DDL1. Therefore we should simply fix the definition of this data name to be equivalent to DDL1. The dREL can construct the DDL1 string using the values in `exptl_crystal_appearance`. It does not seem necessary to create a list-valued version of this data name as it is not referenced anywhere else.

**Comment by vaitkus** [comment]
Issue was resolved by merging PR #325
