### ISSUE TITLE
The _type.contents value 'Uri' should probably be described as a URI reference instead of URI

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#191]
The current description of the 'Uri' content type reads:
```
A Uniform Resource Identifier per RFC 3986
```

However, technically this definition restricts the values to absolute URIs. While this definition works for the `_dictionary.uri` data item which itself requires an absolute URI, items like `_import_details.file_id` allow the use of both absolute and relative URIs.

RFC 3986 acknowledges the usefulness of relative URIs in section 4.1 [1] and defines a more encompassing term "URI reference":
```
A URI-reference is either a URI or a relative reference.
```

Maybe the definition in the DDLm dictionary should be updated accordingly?

[1] https://tools.ietf.org/html/rfc3986#section-4.1

**Comment by jamesrhester** [comment]
I agree with this and see no objections. Can you provide a pull request that makes this change?

**Comment by vaitkus** [comment]
I reopened the issue, since the previously merged PR #193 solved a slightly different problem (although still related to URIs).

I have prepared a separate PR (#196) that expands the definition of the 'Uri' type to allow URI-references. The change is backwards compatible since it allows a larger pool of values for the Uri data items. One drawback of this change is that it is no longer possible to explicitly specify in a machine readable way that only absolute URI values are allowed (i.e. as is required in the case of the `_dictionary.uri` data item). This can still be reflected in the human readable description and examples, but the mismatch will no longer be detected by general-purpose DDLm validators.

On a related note, it would be useful to update the definition of the `_alias.dictionary_uri` data item to clearly state if it requires an absolute URI or an URI reference. By comparison to the `_dictionary.uri` data item, I assume that it is the former (absolute URI), but I was unable to find usage examples to corroborate this. Could you confirm that it is indeed the absolute URI or maybe even update the definition directly in the PR if the proposed solution is acceptable?

Alternatively, we could have two separate data types ('Uri' and 'Uri-reference') to indicate the difference in a machine readable way.

**Comment by jamesrhester** [comment]
Whoops, I missed the opportunity to update the `_alias.dictionary_uri` as well. It should be an absolute URI. I will do a direct edit.

**Comment by vaitkus** [comment]
Great, thank you. A minor note: it seems that the `_definition.update` value was not changed after updating the `_alias.dictionary_uri` definition.
