### ISSUE TITLE
Unit of measurement of the _model_site.adp_eigen_system data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#203]
The `_model_site.adp_eigen_system` is defined as a matrix that contains both the eigenvalues and the corresponding eigenvectors. The following evaluation method in provided in the definition:
```
      A    =  _cell.orthogonal_matrix
      U    =  A * _model_site.adp_matrix_beta * Transpose(A) /(2*Pi**2)
 
      _model_site.adp_eigen_system  =  Eigen( U )
```
where `_cell.orthogonal_matrix` is measured in A (`angstroms`) and  `_model_site.adp_matrix_beta` is dimensionless (`none`). From this it would seem matrix U is measured in A^2 (`angstrom_squared`) and so should the eigenvalues **or** the eigenvectors of U as the multiplication of these should result in an object with the same unit of measure as U.

However, since the Eigen(U) contains both the eigenvalues **and** the eigenvectors it is not clear what units of measure should be assigned (`angstrom_squared`, `none` or some kind of  an element-wise mixture of both).

**Comment by jamesrhester** [comment]
Yes, this is a problem with our system. Ideally we should split this into two data names. I will raise it with the DDLM-group.

**Comment by jamesrhester** [comment]
The ddlm group has no objections. I will prepare a pull request.

**Comment by vaitkus** [comment]
PR #214 was successfully merged.
