### ISSUE TITLE
cif_core.dic: are CIF special codes still in use in CIF 2.0 files?

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#208]
CIF special codes [1] were routinely used in CIF 1.1 files to express certain non-ASCII symbols (i.e. Greek letters). CIF 2.0 files have a much greater character set so these special codes can generally be replaced with proper Unicode characters with an exception of a few symbols (i.e. "\\ddb"; delocalised double bond) . Given this, does the aforementioned CIF 1.1 special notation still applies to CIF 2.0 files?

Several instances of such codes are still present in the `cif_core.dic` file (i.e. "\k", "\%", "\q") so I was wondering if they should be replaced.

[1] https://journals.iucr.org/e/services/editguide.html

**Comment by jamesrhester** [comment]
These codes are still available in CIF2.0 for use when writing dictionaries, so there is no need to change anything.

**Comment by vaitkus** [comment]
Great, thanks for clarifying.
