### ISSUE TITLE
cif_core.cif2.dic (cif2-conversion): deprecated data items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#21]
I was wondering what is the official IUCr policy towards the retention of deprecated data items while converting the cif_core.dic from DDL1 to DDLm? Currently, none of the data items that were deprecated in DDL1 are marked as such in DDLm (the ``_symmetry_*`` data items, for example). Furthermore, some of the deprecated data items seem to be described better than their alternatives, i. e. the ``_symmetry.cell_setting`` data item description contains the ``_method.*`` loop where as its newer alternative ``_space_group.crystal_system`` does not.

**Comment by jamesrhester** [comment]
cif_core.cif2.dic is a leftover file from the very beginning of conversion, it should be removed completely from the cif2-conversion branch.  The proper dictionary file, cif_core.dic, does contain the method expression.
I have removed cif_core.cif2.dic from this branch.
The method expression is present for `_space_group.crystal_system` in cif_core.dic, however it contains 'rhombohedral' as an option.

**Comment by jamesrhester** [comment]
I have raised this issue with the IUCr core dictionary management group, see [this message](http://www.iucr.org/__data/iucr/lists/coredmg/msg00323.html)

**Comment by vaitkus** [comment]
Wonderful. However I am still left wondering why the way deprecated data items were marked in the DDL1 was not retained in any form in the DDLm dictionary? It seemed quite flexible.

```
data_related_function
    _definition
;              Specifies the relationship between the defined item and the
               item specified by _related_item. The following classifications
               are recognized.

               'alternate' signals that the item referred to in _related_item
               has attributes that permit it to be used as an alternative to the
               defined item for validation purposes.

               'convention' signals that the item referred to in _related_item
               is equivalent to the defined item except for a predefined
               convention which requires a different _enumeration set.

               'conversion' signals that the item referred to in _related_item
               is equivalent to the defined item except that different scaling
               or conversion factors are applied.

               'replace' signals that the item referred to in _related_item
               may be used identically to replace the defined item.
;
    _name                      '_related_function'
    _category                    related
    _type                        char
    _list                        yes
    _list_reference            '_related_item'
    loop_ _enumeration
          _enumeration_detail
                         alternate  'used alternatively for validation tests'
                         convention 'equivalent except for defined convention'
                         conversion 'equivalent except for conversion factor'
                         replace    'new definition replaces the current one'
```

The solution you proposed works in this specific case, but how would data item deprecation/replacement work in the DDLm context? It is quite reasonable to expect that at some point a need will arise to replace some DDLm data items with those of differing semantics (thus rendering the ``_alias.definition_id`` data item unusable again).

**Comment by jamesrhester** [comment]
It is true that we now have no mechanism for replacement.  It is also true that deprecation without a one-for-one replacement seems to have been a rare event in the 20 years of CIF. It is not even entirely clear that`_symmetry_cell_setting` dataname should be removed, as it corresponds to the Bravais setting in International Tables terms and could be resurrected as such.  Hopefully the core DMG will pronounce on this.

Meanwhile, I will task the DDLm group with considering whether we should find a way to manage deprecation.

**Comment by jamesrhester** [comment]
A new dataname, `definition.replaced_by` has been approved by the DDLm group for use in deprecation. ddl.dic has been updated accordingly.

**Comment by vaitkus** [comment]
Thank you, the ``definition.replaced_by`` mechanism will be really useful when converting some of our dictionaries from ``ddl1`` to ``ddlm``.
