### ISSUE TITLE
Deprecate `_dictionary_valid.application`

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#211]
It is proposed to deprecate vector-valued `_dictionary_valid.application` and replace it as category key using the two components of this vector.

This attribute simply bundles together two other attributes to form a single-name key instead of a double-name key. Any use of this attribute requires unpacking it into individual items, so there is no point in bundling these items together (unlike, say, `_refln.hkl` which forms a vector that can participate in matrix multiplication). As it is only ever used in one place (the `ddl.dic` reference dictionary) the impact of this is restricted to dictionary-handling software that reads in `ddl.dic`.

**Comment by vaitkus** [comment]
[1] links to a relevant discussion in the IUCr [DDLM-GROUP] mailing list.

[1] https://www.iucr.org/__data/iucr/lists/ddlm-group/msg01696.html

**Comment by vaitkus** [comment]
Issue was resolved by merging PR #222.
