### ISSUE TITLE
`_dictionary_valid.option` contradicts `_dictionary_valid.application`

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#212]
The default value of `_dictionary_valid.option` is `Recommended`. The current dictionary does not include a value for this attribute, so it is in all cases `Recommended`. However, `_dictionary_valid.application`, which is constructed from `_dictionary_valid.option` and `_dictionary_valid.scope`, has a variety of values for this attribute, so there is a contradiction.

This can be simply fixed by explicitly including the value of `_dictionary_valid.option` (and scope). Note also #211 .

**Comment by vaitkus** [comment]
The issue was resolved by merging PR #213.
