### ISSUE TITLE
cif_core.dic: the journal_index.type save frame contains strange enumeration values

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#215]
The `journal_index.type` frame contains the following enumeration values:
```
    loop_
      _enumeration_set.state
      _enumeration_set.detail
         O                        '???????? formula ??????????????'
         S                        '???????? structure description ???????'
```
The extra question marks most likely do not have any special meaning and could be safely removed. Are there any objections?

**Comment by jamesrhester** [comment]
I'll just double-check with Brian who is sort of the custodian of the journal category.

**Comment by vaitkus** [comment]
Brian clarified the historical usage of the `journal_index.type` data item (also see ITC Volume G (2005), section 3.2.5.4). Relevant changed to the data item definition were made in PR #217.
