### ISSUE TITLE
cif_core.cif2.dic (cif2-conversion): can _space_group.name_H_M_alt be looped?

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#22]
In DDL1 version of the cif_core.dic the ``_space_group_name_H-M_alt`` was declared as either looped or unlooped. However, the usage of this data item (``_space_group.name_H_M_alt``) is not completely clear in the DDLm version of the dictionary:
1) The data items is assigned to the ``SPACE_GROUP`` category, which in turn is defined as being a ``SET``. If I understand correctly, this would imply that data items belonging to the category cannot be looped;
2) One of the descriptions given in the definition of the  ``_space_group.name_H_M_alt`` data item illustrates the usage of this data item in a loop context: 
```
;         loop_
         _space_group.id
         _space_group.name_H_M_alt
                          '1'   'C m c m'
                          '2'   'C 2/c 2/m 21/m'
                          '3'   'A m a m'
;        'three examples for space group No. 63' 
```
How should this be interpreted?

**Comment by jamesrhester** [comment]
Looping of space_group items does not make sense in the context of a datablock with atomic positions defined with reference to a single unit cell. The DDL1 allowance of looped space group items (which the symmetry dictionary carried on with as well) is therefore interpreted as an oversight. Examination of the CIF files in the COD suggested that no structural reports ever made use of these datanames in loops, and therefore the decision was taken to explicitly restrict the datanames to being single-valued.  The example was left over from a much older version and I have removed it.

**Comment by vaitkus** [comment]
Thank you for a detailed response, that clears things up.

**Comment by jamesrhester** [comment]
The DDL1 dictionary will be replaced by the DDLm dictionary on the IUCr website as soon as the COMCIFS secretary finds the time.   Editing of the DDL1 dictionary is low priority at this point.

**Comment by vaitkus** [comment]
I apologise in advance if this is not the most appropriate place for this discussion, but I would propose considering a slightly different approach towards the deprecation of the DDL1 ``cif_core.dic``.

I fully understand the need to transition from DDL1 to DDLm, however, removing the DDL1 version as soon as the DDLm version is published might not be the most community-friendly solution. Adapting ones software to process DDLm files instead of DDL1 is already a cumbersome task (one has to upgrade ones CIF parser to process CIF2 files as well as update all the dictionary-structure related logic) and adding a layer of changed semantics on top of it is not making it easier in any way. As a result, people might simply avoid migrating to the DDLm version at all and keep using the old DLL1 version (with all the no longer IUCr supported semantics) as long as possible. I propose the following model instead of instant dictionary deprecation:

1) Before the initial release of the DDLm version, update both versions so that they would have equivalent semantics;
2) For a limited period of time (1-2 years) provide both versions on the IUCr website with a clear disclaimer, that the DDL1 version will be deprecated after a certain period and that it should only be
used for transitional purposes;
3) During that period, do not introduce any new semantics, only bug fixes, into the DDL1 dictionary. The DDLm dictionary, however, is free to be modified in any way necessary, including the introduction of new features;
4) After the period is done, remove the DDL1 version all together and forget it (or maybe store it somewhere deep in the archives).

This is somewhat similar to how Ubuntu distribution works -- one is not required to switch to the newest stable version the moment it is released, but is notified that no new features will be introduced from this point on forward and that after a certain moment the OS will no longer be supported by the maintainers. I do understand that this introduces a bit of an overhead, but the benefits are clear:
1) A smooth transition is provided instead of an abrupt change which is always more community friendly;
2) The work of software developers is simplified since the transition does not entail the change in semantics (and nowadays since the CIF is mostly intended to be software-generated I would not underestimate the importance of this point);
3) Semantically incorrect CIFs would no longer be generated by legacy software that uses the DDL1 dictionaries. One cannot reasonably expect one to change their whole software stack immediately, but the replacement of a dictionary file is a much more reasonable task.

If it is the workforce that is lacking, I volunteer to contribute.

**Comment by jamesrhester** [comment]
Thank you for the offer. I think this is a good idea and will contact you directly.
