### ISSUE TITLE
ddl.dic: the use of _description.text attribute should be extended to categories and dictionaries

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#221]
The definition of the `_description.text` data item currently describes the attribute as:
```
The text description of the defined item.
```
However, in practice this attribute is used not only in data item definitions, but also in category definitions and even as the main dictionary description. The description should be updated accordingly.

Alternatively, the use of the  `_description.text` data item could be extended only to categories and a separate data item could be introduced to describe the dictionary. However, this would mostly be done for cosmetic purposes, since `_description.text` attribute is currently the only dictionary-level attribute that does not start with "_dictionary" and therefore looks slightly out of place.

**Comment by jamesrhester** [comment]
See pull request #224 .

**Comment by vaitkus** [comment]
Great, thank you.
