### ISSUE TITLE
ddl.dic: DICTIONARY_VALID loop should be updated

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#226]
The `DICTIONARY_VALID` loop should be updated by declaring several more categories as prohibited in certain contexts. I have compiled a table that reflects the possible changes. The `+` symbol means that the item is allowed in the given context and no change is needed, symbol `-` means that the item should be explicitly prohibited in the given context and `?` means that I am unsure. I would be grateful if someone could check if my assumptions are correct and also clarify the `?` cases.

| Category name | Dictionary | Category | Item |
| ------------- | :-------------: |  :-------------: |  :-------------: |
| DEFINITION_REPLACED | - | ? | + |
| DESCRIPTION_EXAMPLE | - | + | + |
| DICTIONARY_AUDIT | + | - | - |
| DICTIONARY_VALID | + | - | - |
| ENUMERATION_DEFAULT | - | - | + |
| ENUMERATION_SET | - | - | + |
| IMPORT_DETAILS | - | + | + |
| METHOD | ? | ? | + |

**Comment by jamesrhester** [comment]
Nice table.
First to clarify the question marks:
1. Definition_replaced is allowed in Category (when we abandon a whole category, hasn't happened yet?)
2. Method is allowed in Category, but not in Dictionary

Now, I forgot to mention that subcategories are covered by their parent categories. So ENUMERATION is not allowed for Dictionary and Category, and this prohibition extends to enumeration_default and enumeration_set. With these semantics I believe everything in dictionary_valid is correct. I will update the definition for _dictionary_valid.attributes to clarify this.

**Comment by jamesrhester** [comment]
Pull request #227 hopefully clarifies this sufficiently.

**Comment by vaitkus** [comment]
Great, thank you for the clarification. It seems that my software actually already assumes that the child categories are implicitly included, but having this explicitly stated in the definition indeed helps.

The extended explanation covers most of the categories, however, I think that the `DESCRIPTION_EXAMPLE` category should still be prohibited in the dictionary scope (or the definition of the `_description_example.case` data item should be updated accordingly). This is addressed in PR #229.

**Comment by jamesrhester** [comment]
Agreed.

**Comment by vaitkus** [comment]
Resolved by merging PR #227, #229.
