### ISSUE TITLE
DDLm: enumerator sets with no default values

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#23]
It seems that the DDLm does not strictly impose the use of ``_enumeration.default`` data item when  the ``ENUMERATION_SET`` category data items are used, however, in most cases they are given. I was wondering if the omission of the default values in the descriptions of  the ``save_dictionary_valid.scope`` and ``save_import_details.single_index`` data items is intentional.

**Comment by jamesrhester** [comment]
The omission is intentional. Where there is no clear reason or benefit for a default, it is omitted. For example, import_details.single_index is a largely technical dataname required to construct the import_details table and there is no obvious particular entry that might be preferred.
