### ISSUE TITLE
templ_attr.cif: save_colour_hue contains colors that are not defined in save_colour_RGB

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#238]
Definitions of the `model_site.display_colour` and `atom_type.display_colour` data items from the `CIF_CORE` dictionary import both the `save_colour_RGB` save frame (enumeration values) and the `save_colour_hue` save frame (enumeration defaults). However, the enumeration defaults contain several values, that are not present in the enumeration value list. Namely:

- **unknown**. This value could potentially be replaced by CIF special value `?` or explicitly defined as an enumeration value with RGB codes `'[ ?, ?, ? ]'` (similar to the `'[ ., ., . ]'` definition of 'colourless').
- **steel_grey**. Could potentially be replaced with one of the shades of grey that are already defined ('`grey`', '`grey_light`', '`grey_slate`').
- **magenta**. Could potentially be replaced with '`violet_magenta`' that is already defined.

**Comment by jamesrhester** [comment]
As these are display colours I don't think there is any backwards compatibility issue in fixing this.

I think unknown should be `?`. I agree with the magenta suggestion, `steel_grey` can be added to the enumeration list.
