### ISSUE TITLE
templ_attr.cif: save_ion_to_element contains element 'D' that is not defined in save_element_symbol

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#239]
Data item `_atom_type.element_symbol` from the `CIF_CORE` dictionary imports both the `element_symbol` save frame (enumeration values) and the `ion_to_element` save frame (enumeration defaults). However, `ion_to_element` maps isotope `D` to element `D` that is not actually defined in the `element_symbol` save frame.

This could resolved by changing the isotope mapping to '`H`' (hydrogen) in `ion_to_element` or defining a separate deuterium element in `element_symbol`.

**Comment by jamesrhester** [comment]
I think `D` should be added the `element_symbol` save frame, as it is present in all the other tables and is clearly being treated as a separate "element".
