### ISSUE TITLE
The _dictionary.uri value in multiple dictionaries is not a proper URI

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#24]
According to RFC 3986 (http://www.rfc-base.org/txt/rfc-3986.txt) an URI must begin with the scheme name, so ``www.iucr.org/cif/dic/ddl.dic`` should be changed to one of the following ``http://www.iucr.org/cif/dic/ddl.dic``, ``http://iucr.org/cif/dic/ddl.dic``, ``ftp://iucr.org/cif/dic/ddl.dic``, etc.

**Comment by jamesrhester** [comment]
I agree that the URIs should be updated to begin with http:// (ftp:// would also work).  I will do this.

**Comment by jamesrhester** [comment]
It may be sensible to give each dictionary a DOI, for better permanency, in which case the URI would be of the form 'http://dx.doi.org/...'. I am consulting with the IUCr on whether this will be possible.

**Comment by merkys** [comment]
Addressed in PR #137 for `cif_core.dic`.

**Comment by jamesrhester** [comment]
The issue with DOIs is still under consultation so I will close this as the PR provided a sufficient workaround.
