### ISSUE TITLE
cif_core: specify the author name format for people who only have a single name

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#240]
The `_publ_author.name`, `_audit_author.name` and other similar data items currently specify the following author name format:
```
The family name(s), followed by a comma and including any
dynastic components, precedes the first name(s) or initial(s).
```
However, this definition does not specify how situations when author only has a single name should be handled. Having only a single name seems to be a common occurrence among people from Indonesian or southern India as detailed in this article from Nature [1]. Several examples of such name usage in scientific journals:

* Nithinchandra (*Acta Crystallographica, Section E*, [[2]](https://scripts.iucr.org/cgi-bin/paper?S1600536813029425)).
* Chandra (*Acta Crystallographica, Section E*, [[3]](https://scripts.iucr.org/cgi-bin/paper?S2056989015014425)).
* Shally (*Organic & Biomolecular Chemistry*, [[4]](https://pubs.rsc.org/en/content/articlelanding/2020/OB/D0OB00998A))).
* Nitisha (*The Journal of Organic Chemistry*, [[5]](https://pubs.acs.org/doi/10.1021/acs.joc.9b01223)).

It might be useful to update the current author name format and examples to cover such cases.

[1] https://www.nature.com/articles/d41586-020-02761-z
[2] https://scripts.iucr.org/cgi-bin/paper?S1600536813029425
[3] https://scripts.iucr.org/cgi-bin/paper?S2056989015014425
[4] https://pubs.rsc.org/en/content/articlelanding/2020/OB/D0OB00998A

**Comment by jamesrhester** [comment]
Yes, I agree that this should be done.
