### ISSUE TITLE
cif_core.dic: the 'units.code' data item is never imported

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#25]
The ``_units.code`` data item is referenced multiple times in the ``cif_core.dic``, but it is not defined nor explicitly imported to the dictionary. Based on the values I assume that it is equivalent to the ``_units_code`` data item found in the ``templ_enum.cif`` file, however, it does not contain the ``_unit.code`` data name as one of its aliases.

**Comment by jamesrhester** [comment]
`_units.code` is a DDLm attribute, which is defined in the DDLm attribute dictionary ddl.dic, so on this basis it may be used freely in DDLm dictionaries. The `units_code` save frame of the `templ_enum.cif` file is imported into the `_units.code` definition, thereby populating the enumerated list of possible units.  Essentially, the contents of the `units_code` save frame is inserted into the `_units.code` definition in ddl.dic.

Note that this behaviour is different to DDL2, where the units are listed in (each) domain dictionary top level datablock, in `_item_units_list.code`

**Comment by vaitkus** [comment]
Thank you for explaining, that was an oversight on my part.
