### ISSUE TITLE
ddl.dic: remove `_description.common` from the recommend item list

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#263]
DDLm reference dictionary recommends that the `_description.common` attribure should appear in the `Item` scope definitions (see the `DICTIONARY_VALID` loop). However, this recommendation does not seem to be followed even in dictionaries that are managed by COMCIFS. I suggest to remove this specific attribute from the recommended list altogether.

Several other recommended attributes are also often omitted from data item definitions (e.g. `_definition.scope`, `_definition.class`), but at least these attributes have default values.

**Comment by jamesrhester** [comment]
Syd has explained it thusly:

> It simply provides a short text identity of the defined item, as opposed to the  ‘_description.text’ which gives a more detailed explanation of the purpose of the item. I think it was asked for to provide quick and unique recognition because some of the DDL names really have a convoluted ‘reverse construction' and others look very similar (or are in numerated sequences). If this item is applied properly and consistently in the dictionaries I think it could be really beneficial to comprehension, especially for non-experts wanting to quickly grasp what an item represents.

So the problem is really that nobody has felt the need to take advantage of this data name. However, one can imagine dictionary-writing tools that use `_description.common` to provide prompt text in a GUI, and my hope is that more such tools will appear in the future. So I am thinking we might leave it in for now.

**Comment by jamesrhester** [comment]
I just realised that the suggestion was simply to remove `_description.common` from the recommended item list, not to remove it completely, sorry, my mistake. I agree that it makes no sense that it is recommended and almost never used. Perhaps @vaitkus could prepare a PR?
