### ISSUE TITLE
Handling loops during 'if_dupl' imports

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#264]
A thorough reviewer of the DDLm chapter has noted that the behaviour of imports in the case of `if_dupl` = `Replace` needs clarification in the particular case where a single packet loop is presented as unlooped data items. If the importing definition has two data names from the category, and the imported definition has only one of those two, then it is possible that only the duplicated data name will be replaced, leading to incorrect results (as the unduplicated value presumably was relevant only to the previous, replaced value).

I propose explicitly stating that all data items in a category are replaced, or removed if not present in the imported definition, which I think is the intended behaviour. Any comments?

**Comment by jamesrhester** [comment]
Actually, we need to be careful as e.g. the `name` category might have `_name.linked_item_id` in the imported definition, but necessary has `_name.object_id` in the importing definition. Following my suggested rule would nuke `_name.object_id`. So a blanket replacement or removal of items in a category is not correct. Better to say that this applies only to `Loop` categories?

**Comment by jamesrhester** [comment]
As there have been no objections I will enshrine this in text in the DDLm chapter as follows and provide an update to ddl.dic:

> Note that if any attribute from a Loop category appears in the imported definition when replacing on import, all attributes
> from that category are first removed from the importing definition
> before importation, in order to avoid potential mismatches in looped values.

**Comment by jamesrhester** [comment]
Further updated text:

> Note that if any attribute from a Loop category appears in 
> both the 
> importing and imported definition, all attributes
> from that category are either removed from the importing definition
> before importation ('Replace' option), or collectively ignored 
> ('Ignore' option), in order to avoid potential 
> mismatches between looped values in the resulting dictionary.

**Comment by vaitkus** [comment]
Looks good!
