### ISSUE TITLE
cif_core.dic (cif2conversion): default enumeration value is out of enumeration range

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#27]
Data items ``_chemical_conn_bond.distance`` and ``_chemical_conn_bond.distance_su`` have the default enumeration value of ``0.0``, even thought the enumeration range is ``0.5:``.

The ``_chemical_conn_bond.distance_su`` data item should probably also have the enumeration range of ``0.0:`` since it stores the standard uncertainty.

**Comment by jamesrhester** [comment]
This is clearly an error in the dictionary. The aliased dataname, `chem_comp_bond.value_dist` in the macromolecular CIF has a minimum value of 0.0 and no default value.  Clearly a default value for a bond distance is impossible.
