### ISSUE TITLE
cif_core.dic: add an upper range for the `_space_group_symop.id` data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#277]
The `_space_group_symop.id` data item serves as the key of the  `SPACE_GROUP_SYMOP` category and is defined as an integer in the range of `[1; +inf)`. However, since no space group has more than 192 unique symmetry operations, the upper range of 192 could also be assigned.

Note, that this would also help to ensure that the `symop` data items (e.g. `_geom_angle.site_symmetry_1`) are assigned reasonable values like `190_555` and not something like `1234567_555`.

**Comment by jamesrhester** [comment]
I think this should be OK as the higher-dimensional space groups use a different category to record their symops.
