### ISSUE TITLE
cif_core.dic (cif2conversion): enumeration ranges of *_su data items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#28]
Multiple data items in the ``cif_core.dic`` and ``templ_attr`` that are meant to store standard uncertainties of measurand data items have incorrect (or missing) enumeration range definitions. I assume that the SU values are meant to always be greater than 0, but some *_su data items have enumeration values lower than 0. Also, some *_su data items are marked as being of the Real type (-inf;+inf), but do not have an enumerator range specifying that the negative values are not allowed. The issues: 

``templ_attr``:
```
Data items with explicit negative range values:
_Cartn_coord_su [-1000.:1000.]
_fract_coord_su [-1.:1.]

Data items that are marked as Real with no enumeration range:
save_aniso_BIJ_su
_aniso_UIJ_su
```
``cif_core.dic``:
```
Data items with explicit negative range values:
_geom_hbond.angle_DHA_su _enumeration.range [-180.:180.]

Data items that are marked as Real with no enumeration range:
_refine_diff.density_max_su
_refine_diff.density_min_su
_refine_diff.density_rms_su
_refine_ls.abs_structure_Flack_su
_refine_ls.abs_structure_Rogers_su
_refln.F_meas_su
_refln.F_squared_meas_su
_geom_angle.value_su
_geom_torsion.angle_su
```

**Comment by jamesrhester** [comment]
I think it is reasonable to assume that a value with `_type.purpose` of `SU` will be positive real, with no need for an explicit enumeration range. I suggest that any `_enumeration.range` attributes be removed from all SU definitions. Agreed?

**Comment by vaitkus** [comment]
I would actually prefer having an explicit enumeration range for the ``SU`` data items for formal validation purposes. The lower bound should clearly be ``0.0``; the upper bound should probably depend on the measurand data item (i. e. having ``SU`` greater than 360 for the ``_geom_hbond.angle_DHA_su`` looks strange considering the [-180.:180] enumeration range, although, still technically correct).

The parenthesis notation used in DDL1 does not allow to specify negative ``SU``'s in any way ("3.14(-1)" is not an allowed number) and having explicit enumeration ranges in the ``*_SU`` notation would help ensure the equivalence of these two notations. Or is that too much of an overhead?

**Comment by jamesrhester** [comment]
Step one should be to make sure `_type.purpose` is set to `SU` for all `*_su` datanames and `_name.linked_item_id` to the corresponding dataname.  We could state in the entry for `SU` in `_type.purpose` that such a number must be a positive real. This fact can then be hard-coded into validation software, which could now additionally check that any `_enumeration.range` that is given starts at zero for SU items. I'd prefer to minimise the amount of redundancy in the dictionary text to maintain readability, and in this case both human and computer readers already understand that the value must be positive, so leaving out `_enumeration.range` is reasonable. 
Likewise for upper bounds, it is easy enough for validation software to check the bounds on the related item and calculate what it thinks the maximum SU could be.
I think we should leave this issue open until at least all SU in the dictionary have been flagged as such.

**Comment by jamesrhester** [comment]
An updated version of cif_core.dic has now been committed. All SU items should have `_type.purpose` SU, no `_enumeration.range`, and a correct `_name.linked_item_id`.

**Comment by vaitkus** [comment]
Thank you for the corrections.
