### ISSUE TITLE
templ_attr.cif: save frame `save_matrix_w` contains the `_name.category_id` attribute

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#282]
Draft version of IT, Vol. G states that:
```
Definition blocks in a template dictionary will not contain _definition.id,
_name.object_id, or _name.category_id attributes, as these values are
different for every definition.
```
However, the `save_matrix_w` save frame from the `templ_attr.cif` file contains the `_name.category_id` attribute with value `cell_subsystem`. It seems that this save frame is imported by multiple definitions from the Modulated Structure (CIF_MS) dictionary [1].

Would it make sense to copy the `_name.category_id` attribute to all of the importing frames and remove it from the imported frame to adhere to the text in IT, Vol. G?

[1] https://github.com/COMCIFS/magnetic_dic

**Comment by jamesrhester** [comment]
This was an oversight in Volume G draft chapter, I will instead edit the chapter to allow `_name.category_id` in template dictionaries.

**Comment by vaitkus** [comment]
Acknowledged. I view the issue as resolved, however, I will leave it up to you to close the issue (in case it still serves as a reminder).
