### ISSUE TITLE
ddl.dic: relax requirements of the 'Implied' container type

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#286]
The description of the `_type.container` states that:
```
<...> 'Implied' may only be used in the DDLm Reference
Dictionary for attributes whose types are linked to the values
of other attributes.
```
This description was probably written with the `_enumeration_default.value` attribute in mind, however, the `Implied` container is now also assigned to the `_description_example.case` and `_enumeration.default` attributes which do not seem to link to values of other attributes. The description should be updated to reflect the new usage.

**Comment by jamesrhester** [comment]
I agree these should be updated.
