### ISSUE TITLE
ddl.dic (cif2-conversion): ATTRIBUTES save frame contains no _name.category_id

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#29]
The ``_name.category_id`` data item is marked in the ``_dictionary_valid.application`` loop as being mandatory in the Category scope, however, the ``ATTRIBUTES`` save frame does not contain it. Since it is declared as the ``Head`` category of the dictionary, maybe marking it as being the container category of itself would work?

On a related note, the head ``CIF_CORE`` category in the ``cif_core.dic`` dictionary has the ``CIF_DIC`` as its container category, even though such category does not seem to be defined anywhere.

The ``_audit.schema`` save frame in the ``cif_core.dic`` is also missing the ``_definition.update`` data item.

**Comment by jamesrhester** [comment]
The convention has been for the category ID of the Head category to be the dictionary.title of the enclosing data block.  This should be corrected for cif_core, and mentioned as a special case for the Head type category in the definition of _definition.class in ddl.dic

_audit.schema is a new definition and _definition.update was overlooked.

**Comment by jamesrhester** [comment]
_audit.schema fixed and Head category also fixed.  The latter involved renaming the dictionary data block and title to avoid name clashes.

**Comment by vaitkus** [comment]
Thank you for the correction.
