### ISSUE TITLE
Optimal description of save_site_symmetry definition in templ_attr.cif

### ISSUE THREAD

**Issue by nautolycus** [COMCIFS/cif_core#295]
The current definition of save_site_symmetry definition in templ_attr.cif reads:

;
     The set of data items which specify the symmetry operation codes
     which must be applied to the atom sites involved in the geometry angle.

     The symmetry code of each atom site as the symmetry-equivalent position
     number 'n' and the cell translation number 'pqr'. These numbers are
     combined to form the code 'n pqr' or n_pqr.

     The character string n_pqr is composed as follows:

         n refers to the symmetry operation that is applied to the
         coordinates stored in _atom_site.fract_xyz. It must match a
         number given in _symmetry_equiv.pos_site_id.

         p, q and r refer to the translations that are subsequently
         applied to the symmetry transformed coordinates to generate
         the atom used in calculating the angle. These translations
         (x,y,z) are related to (p,q,r) by the relations
              p = 5 + x
              q = 5 + y
              r = 5 + z
;

I suggest two improvements:

[1] First sentence to read: 
"Data item specifying the symmetry operation codes applied to the atom sites involved in a specific geometric configuration."

"Data item" instead of "The set of..." since this text may appear in the definition of each individual entry, e.g. _geom_angle.site_symmetry_1 , _2 etc.

"a specific geometric configuration" since they are used for distances as well as angles.

[2] Second sentence of para 4 to read:

"It must match a number given in _space_group_symop.id (or one of its aliases such as _symmetry_equiv_pos_site_id)"

since _space_group_symop.id is the "head word" (i.e. _definition.id); but it's useful also to give an alias since the _symmetry_equiv... items are probably the most widespread in currently extant CIFs.

**Comment by jamesrhester** [comment]
Sounds good to me. I don't think we should as a rule keep referring to DDL1 equivalents as that will significantly expand the dictionary but it is good to remind programmers of the aliases for high-profile data names.
