### ISSUE TITLE
ddl.dic: specify that the `version` content type follows the syntax of SemVer 2.0 

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#312]
Currently, the `version` content type is defined as:
```
version digit string of the form <major>.<version>.<update>
```
However, this syntax is not compatible with pre-release version numbers such as `1.2.3-dev-17` usage of which is recommended by the COMCIFS [dictionary development guidelines](https://github.com/COMCIFS/comcifs.github.io/blob/master/accepted/dictionary_development_practices.md). Adopting an external standard such as the Semantic Versioning (SemVer) may solve this issue with little effort.

The Semantic Versioning specification version 2.0.0 ([SemVer](https://semver.org/spec/v2.0.0.html)) provides a well defined version number syntax and even a formal Backus-Naur form grammar that seems compatible with the needs of DDLm. ~~However, we should be careful to explicitly specify that the DDLm version number strings adopt only the syntax and precedence rules, but not the full semantics since, as I recall, there was a decision to generally not increment the `<major>` version number.~~

One little existing incompatibility is that the current version of the dictionary development guidelines suggests using a dash to separate pre-release version components instead of a dot (`1.2.3-dev-17` instead of `1.2.3-dev.17`). While the usage of a dash still results in a valid semantic version number, it is not compatible with the given precedence rules (`1.2.3-dev-10` would be considered lower than `1.2.3-dev-2`). I have issued a PR (https://github.com/COMCIFS/comcifs.github.io/pull/16) to the COMCIFS guidelines with an appropriate fix.

Edit 1:
Added a strike through the part which states that we do not want to follow the semantics of the SemVer version numbers.
While we might not want to increment the major version number of the DDLm reference dictionary, other dictionaries (e.g. `CIF_CORE` or external ones) do not have the same limitations.
Edit 2:
Added the reference to the COMCIFS guideline PR.
Updated the precedence rule failure example.
Corrected several grammatical issues.

**Comment by jamesrhester** [comment]
I agree with this. We need to improve the explanation of how to determine whether or not a change is major/minor/patch in the dictionary development guidelines, something like:

1. major: incompatible change in data name meaning 
2. minor: addition of one or more new data names (except those already implied by existing names, i.e. `_su`)
3. version: improvement in existing data names, fixing of bugs

We are unlikely to ever change the major number as far as I can tell.

**Comment by vaitkus** [comment]
I filed the proposal to provide explanation on the version number selection as a separate issue: https://github.com/COMCIFS/comcifs.github.io/issues/17.
