### ISSUE TITLE
Should `_type.purpose  Key` data items be case-sensitive?

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/cif_core#316]
As remarked upon [here ](https://github.com/COMCIFS/cif_core/pull/313#pullrequestreview-1190337125), data items in the core dictionary with `_type.purpose` given as `Key` have `_type.contents` variously defined as `Code`, `Word`, or `Text`.

`Code` is a case-insensitive sequence of CIF2 characters containing no ASCII whitespace.
`Word` is a case-sensitive sequence of CIF2 characters containing no ASCII whitespace.
`Text` is a case-sensitive sequence of CIF2 characters.

Given that a `Key` should have a unique value within a looped list, does it make sense for the contents of the key to be case-sensitive? ie `Word` or `Text`?

**Comment by jamesrhester** [comment]
"Uniqueness" is relative to the meaning of "==", so if A==B then they are not unique. "==" can be a case-insensitive or case-sensitive comparison. I agree that in general case-sensitivity is expected, but I think we can leave dictionary authors to decide whether they care about case and perhaps advise to choose case-sensitivity by default.

**Comment by vaitkus** [comment]
I fully agree with the points made by @jamesrhester. While I personally would always recommend to use case-sensitive identifiers without whitespaces (i.e. `Word`) where possible, we should definitely allow most other content types to ensure compatibility with external keys or legacy CIF files that were written against DDL1.

Given this, I guess that it would make sense to go though the current version of the `CIF_CORE` dictionary and update the content types of id items to `Word` where possible (e.g. `_geom_hbond.id` and `_geom_torsion.id` probably do not need to be of the `Text` content type).

**Comment by jamesrhester** [comment]
I agree it would be good to do a janitorial fix changing `Text` to `Word` where whitespace would not be expected (or is absent in COD).
