### ISSUE TITLE
cif_core.dic (cif2-conversion):  _type.contents value 'Symop' 

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#32]
The ``_function.Symop`` save frame in the ``cif_core.dic`` and the ``site_symmetry`` save frame in the ``templ_attr.cif`` contain the ``_type.contents`` data items with the value 'Symop'. This value, however, does not seem to be defined as one of the possible enumerator values of the ``_type.contents`` data item.

**Comment by jamesrhester** [comment]
We can add 'Symop' to type.contents with meaning 'a string containing no whitespace and commencing with a postiive integer, followed by an underscore and then three or more digits'.  Alternatively we can simply replace 'Symop' with type 'Text'.  Of these alternatives I would prefer that 'Symop' be added to _type.contents as it provides more fine-grained typing information.

**Comment by vaitkus** [comment]
I would also prefer having the 'Symop' content type. However, won't allowing "three or more digits" after the underscore cause an ambiguity in certain cases? I mean, when there are more that 3 digits, it is not clear how they should be interpreted, i. e.: 1_1234, could be interpreted as having three different meaning: 1_{12}{3}{4}, 1_{1}{23}{4} and 1_{1}{2}{34}.

Another problem arises from the fact that we could potentially end up with negative numbers if any of the translations is greater than 5, i. e. a translation of [ -6, 0, 0 ] would produce a symop of 1_{-1}{5}{5}

Maybe there are already standard ways to handle such situations?

If not, I have two proposals that address these issues:
#### 1. Increasing the number of allocated digits on demand
##### 1.1.  Translations greater than 4
If the translation vector component takes more than one digit to denote in the symop (as is true with any translation > 4 following the [555] notation), than the same number of digits could be allocated to all vector components. Following the previous example, ``1_{12}{3}{4}`` would become ``1_{12}{03}{04}``, ``1_{1}{23}{4}`` would become ``1_{01}{23}{04}`` and ``1_{1}{2}{34}`` would become ``1_{01}{02}{34}``. This would add the additional restriction to the number of trailing digits (it would always have to be a multiple of 3), but would remove the ambiguity.

##### 1.2. Translations lesser then -5
If the translation becomes negative in the symop (as is true with any translation < -5 following the [555] notation), the index of the base unit cell could be changed from [5, 5, 5] to the one that allows avoiding negative numbers. The rules for determining such index could be summarised as:

Let **V** = [ **v1**, **v2**, **v3** ] be the translation vector;
Let **B** = [ **b**, **b**, **b** ] be the base unit cell index;
Let **b** = 5 * 10^**n**, where **n** is natural number (including the zero).

Then such **n** should be selected that for each v1, v2, v3 the following condition is true:
-(5 * 10^**n**) < **v**{1,2,3} < (5 * 10^**n**) - 1

##### 1.3. Combining both approaches

In order to unambiguously accommodate both 1.1 and 1.2 approaches, the base unit cell index change rule would have to be applied every time. The approach would probably be best illustrated with a few examples: 

| Translation V  | n | V component value range  | Base unit cell index  | Symop  |
|:---:|:---:|:---:|:---:|:---:|
| [ -1, 0, 0 ] | 0 | [ -5; 4 ] | [ 5, 5, 5 ] | 1_455 |
| [ 0, 0, 16 ] | 1 | [ -50; 49 ] | [ 50, 50, 50 ] | 1_505066 |
| [ -6, 0, 0 ] | 1| [ -50; 49 ] | [ 50, 50, 50 ] | 1_445050 |
| [ -6, 48, 49 ] | 1 | [ -50; 49 ] | [ 50, 50, 50 ] | 1_449899 |
| [ -51, 0, 0 ] | 2 | [ -500; 499 ] | [ 500, 500, 500 ] | 1_449500500 |

Following the previous example, ``1_{12}{3}{4}`` would become ``1_{57}{48}{49}``, ``1_{1}{23}{4}`` would become ``1_{46}{68}{49}`` and ``1_{1}{2}{34}`` would become ``1_{46}{47}{79}``

#### 2. Introducing a digit separator when needed
In order to accommodate negative and multi-digit translation components a separator symbol could be used when needed. Following the previous example and choosing '|' as the separator, ``1_{12}{3}{4}`` would become ``1_12|3|4``, ``1_{1}{23}{4}`` would become ``1_1|23|4`` and ``1_{1}{2}{34}`` would become ``1_1|2|34``.

More than 3 trailing digits are probably not very likely, but covering these situations in advance might prove useful in the future. Both approaches seem to be compatible with the current usage, however I would prefer the 1. What is your opinion on this?

**Comment by merkys** [comment]
I would vote for proposition **1.3** as a homogeneous extension of the current three-digit translation symbols. Proposition **2** would introduce negative offsets and separators, and retaining the +5 rule would be awkward for translations >= 6.

**Comment by jamesrhester** [comment]
Unfortunately we are tightly bound by current usage. `Symop` is meant to describe strings of the form 'nn_nnn' as defined in the DDL1 dictionaries. See for example the geom_angle_site_symmetry_* items.  To maintain equivalence we cannot redefine the construction or interpretation as software has been written that inputs/outputs these items. My reason for allowing more than three digits after the underscore in the `_type.contents` definition was to allow for modulated structures, which may have more than three dimensions for the translations.

Anyway, it seems we are all agreed on adding `Symop` back to the list of possible types.

[It has been noted](http://www.iucr.org/__data/iucr/lists/ddlm-group/msg01519.html) that the traditional single-digit Symop format does cause problems for the macromolecular people. We may yet introduce a more sophisticated way of compactly describing site symmetries when this problem arises, but that would have to be in a new dataname.  In any case, we don't need to define a new type now.

**Comment by vaitkus** [comment]
Understood. Then adding the ``Symop`` enumerator value would do just fine.

**Comment by jamesrhester** [comment]
Updated ddl.dic in repository.

**Comment by vaitkus** [comment]
Thank you for the update.
