### ISSUE TITLE
ddl.dic (cif2-conversion): _type.container definitions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#33]
The '_type.container' enumerator value descriptions seem to be a bit incorrect. The "Array", "Matrix", "List" and "Table" values are described as having elements separated by commas, however, according to the CIF2 syntax elements in arrays and tables should be separated by white spaces.

**Comment by jamesrhester** [comment]
This is a mistake in ddl.dic. The original STAR2 format on which CIF2 was based used commas where CIF2 uses whitespace. This will be corrected.

**Comment by jamesrhester** [comment]
I have just committed a change to ddl.dic that removes format-specific descriptions for _type.container values.

**Comment by vaitkus** [comment]
Thank you for the fix.
