### ISSUE TITLE
Add a disclaimer about the historic misuse of the _atom_site_symmetry_multiplicity data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#331]
In the DDL1 version of the dictionary, the `_atom_site_symmetry_multiplicity` data item is deprecated and an appropriate explanation is provided in the description:
```
The multiplicity of a site due to the space-group symmetry as
given in International Tables for Crystallography Vol. A (2002).

Use of this data name is deprecated because of
inconsistencies in practice among structure refinement
software packages. The number of positions given for
this Wyckoff site in International Tables for
Crystallography Vol. A (2002). should now be expressed
using the data name _atom_site_site_symmetry_multiplicity.
In the historic archive some CIFs use this item to give values
that belong in _atom_site_site_symmetry_order.
```
However, the DDLm dictionary treats this data name as a simple alias of `_atom_site.site_symmetry_multiplicity` without providing any details. I do not think that it is worthwhile to split `_atom_site_symmetry_multiplicity` into a separate data item simply to deprecate it, but maybe a disclaimer of some sorts could be included in the definition regarding the historic misuse? This could potentially lead to a better interpretation of archival CIF files.

Should this disclaimer be added or should this be treated as a misuse of DDL1 that does not transfer to DDLm?

**Comment by jamesrhester** [comment]
I'm glad you spotted this. I think a note should be added to the DDLm definition:

"The `_atom_site_symmetry_multiplicity` form of this data name is deprecated because of historical inconsistencies in practice among structure refinement software packages and should not be used."
