### ISSUE TITLE
ddl.dic (cif2-conversion): _type.container 'Multiple' / _type.contents values

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#34]
The ``_type.container`` data item in the ``DDLm attribute dictionary`` has ``'Multiple'`` as one of its available values. The description of this data item states that the value ``'Multiple'`` allows:
```
values as List or by boolean ,|&!* or range : ops
```
The given definition seems a bit ambiguous and I was hoping that you could clear a few things up:
1) Are the three given expressions (list, boolean and range) mutually exclusive or can they be used in the same context. For example:
    1.1) can a list contain boolean or range expressions?
    1.2) can ranges be used in boolean expressions, etc.
2) Lists:
    2.1) Can lists be nested? If yes, then is there a limit to the maximum nesting depth?
3) Boolean:
    3.1) What is the set of the allowed boolean operations and what does each of the operators mean?
    The '&' (and),  '|' (or) and '!' (not) operators are used widely in multiple programming languages,
    but the ',' and '*' might have different meanings depending on the implementation.
    3.2) are parentheses allowed in the boolean expression?

A related set of questions deals with the ``_type.contents`` values in the ``cif_core`` dictionary.
It is marked as being an enumerator, however, in several cases composite values are used instead of a single enumerator:
- ``_model_site.adp_eigen_system``: ``List(Real,Real,Real,Real)``
- ``_atom_type_scat.versus_stol_list``: ``List(Real,Real)``
- ``_function.Closest`` : ``Matrix(Real,Real,Real)``

Most of the questions related to these observations overlap with those given about the ``_type.container`` data item, however, some do not:
1) Are these composite values intentional or are they a leftover from previous revisions? I assume that such values are made legit by the``_type.container`` value ``'Multiple'`` in the ``_type.contents`` data item definition, however, this seems to conflict with the COMCIFS policy to "not to allow changing
the interpretation of a dataname based on the values of other datanames";
2) The List(*) notation is given in one of the examples, however, the Matrix(*) notation is not mentioned in any of the descriptions. Is it allowed or is that a mistake?

Finally, I think that the majority of my questions are easily answered by a formal grammar definition of the field values. Even if the dictionaries are primarily intended for human readers, the grammar removes a lot of ambiguity (as well as makes life much easier for programmers). I have composed an EBNF grammar ([type-contents.txt](https://github.com/COMCIFS/cif_core/files/955509/type-contents.txt)) for the ``_type.container`` data item values based on a few assumptions:
1) The enumerators appearing in the values are case-insensitive;
2) There is no list nesting limit, that is the ``Integer,Real,Binary``,  ``Integer,List(Integer,Real)`` and ``List(List(List(Name,Tag),Integer,Real),Binary),Octal`` are all valid values;
3) The boolean expressions are allowed inside lists, i.e.: ``Text|Real,Real&!Integer|Range`` and ``List(Text|Real,!Integer)`` are both valid values;
4) Only the  '&' (and),  '|' (or) and '!' (not) boolean operators are supported, but not ',', '*' since I am currently unsure of their interpretation;
5) The range syntax is not covered at all (should not matter in this context).

This is only the initial version and I could modify it based on your feedback. Maybe you could provide some example values that should and should not validate?

I you agree that such specification (in one form or the other) would be of value to the dictionary users, maybe a data item could be introduced to store this kind of specification in the dictionary as well (i.e. ``type.contents_grammar``)? The formats of other values, such as symmetry operators, chemical formulae, etc. could also eventually be described in an unambiguous, machine-readable way.

**Comment by jamesrhester** [comment]
The original idea for `_type.contents` envisaged arbitrary datavalue complexity,  Part of the driver for this was the perceived need to put all loop key datanames together into a single 'master key' dataname. This approach has been dropped, so almost all datanames have a much simpler structure.  Datanames with heterogeneous values are unlikely to be common, as each component would need to be treated in a different way and so would more natrually be defined separately.  So my initial response is that we no longer need these complex structures, indeed the only place that `_type.container` of `Multiple` occurs is in the definition of `_type.contents`, and the most complex `_type.contents` that we have are those that @vaitkus has identified.

At this point I think it would be worth describing a simple grammar that only included points (1) and (2). I don't think it is worth developing a grammar that can describe arbitrarily complex data values until such data values actually appear, which I suspect is unlikely.  At this point we can simplly reserve the relevant characters (&|*.).

It is correct to say that a `_type.container` value of `Multiple` implies that combinations of the items in the `_type.contents` list becomes possible, and that this violates the principle that interpretation of one dataname should not depend on the value of another.  One way around this is to define a separate attribute, e.g. `_type.compound_contents` which contains this information.  In this case `_type.container` of `Multiple` is replaced by `List` or `Single`. So we might have:

```
_type.container List
_type.contents Compound    #New enumerated value
_type.compound_contents  "List(Real,Integer,(Text,Integer),Text)" #The contents of each list element
```

How does that sound?  The definition for `_type.compound_contents` would include the grammar that you have developed.

A lot of these `_type` attributes were developed to allow for transforming dREL methods into typed languages.  So the transforming function would be able to emit the type of the function as well as the types of the parameters. Ideally we would make sure that we can preserve this ability.

**Comment by vaitkus** [comment]
I fully agree that things should not be made too complex in advance. The proposed ``_type.compound_contents`` seems quite flexible; I could easily modify the grammar to only include (1) and (2) for now.

By the way, the example that you provided (``List(Real,Integer,(Text,Integer),Text)``) does not fit the grammar since any nested list must be prefixed with the ``List`` keyword (the correct version in this case should be ``List(Real,Integer,(Text,Integer),Text)``). Is this acceptable or should I modify the grammar in some way? Also, should I include the ``Matrix`` keyword in the grammar as well?

I am very happy that you are considering including the grammar in the description, however, I would really suggest defining a separate data item for that purpose. The data item could have the ``_type.purpose`` value set to ``Encode`` thus explicitly stating that it can be automatically processed
(i. e. for automatically generating a parser). Having a separate data item would also open the door to eventually providing machine-parsable descriptions to other data items as well.

**Comment by jamesrhester** [comment]
Yes, I have made a mistake in the example, you are correct that `List` was missing. `Array` and `Matrix` are also container types, so can be included, although it may be difficult to detect any difference between an `Array` and a `Matrix` purely by inspection of the structure or element type.
I am reluctant to define a separate data attribute for machine-readable grammars, mostly because very few dataitems in general should have structure. As I have explained above, any non-uniform structure within a datavalue means that datavalue could be decomposed into distinct parts.  So I think we need to wait and see whether or not there is any need for descriptions of internal structure before defining a new data attribute.

**Comment by vaitkus** [comment]
I have updated the grammar ([type-contents-simplified.txt](https://github.com/COMCIFS/cif_core/files/986540/type-contents-simplified.txt))  in regards to your recent comments. I also included additional restrictions on the Matrix and Array containers based on their description in the ``_type.container`` description -- these containers are not allowed to nest other containers and can only contain numerical data types. Please let me know if I should change that.
 
I agree that probably very few items will have an intricate internal structure, but even the simple ones would benefit from the formal grammar. For example, the ``_enumeration.range`` description (_The inclusive range of values "from:to" allowed for the defined item_) leaves some room for interpretation:
1) Can a range be defined without the lower (i.e. ':10') or the upper bound (i.e. '0:')?
2) Can symbol ranges (i.e. 'a:z') be defined as well as number ranges?
3) Can non-continuous ranges be defined (i.e. '1:11,12:42'), etc.?

Ambiguities like these can be clarified with several more sentences to the description and a few more examples, or/and a formal grammar (which would actually allow one to validate the provided examples). Of course, one can always add the explanatory grammar to the description, but so can the value of any other data item. Having a separate data item designated just for this purpose seems like a more ontologically elegant solution and it might even encourage developers of other DDLm dictionaries to include grammar definitions into their own dictionaries.

In any way, I would be glad for the grammar definitions to be included in any form.

**Comment by vaitkus** [comment]
As the `_type.container` and `_type.contents` have been greatly simplified in recent revisions (i.e. the `Multiple` container type was removed), the majority of this discussion is probably no longer relevant. However, I think that the idea of introducing an attribute intended to store a formal grammar that describes all possible attribute values is still worthwhile pursuing, so I might open a separate issue on this topic in the future.
