### ISSUE TITLE
Contradictory definition of _citation_editor.id

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#346]
The `_citation_editor.id` is defined as having a `Single` container with an `Implied` content type. However, the evaluation dREL of this item defines it as an Array of two elements:
```
    _citation_editor.id = [_citation_editor.citation_id,_citation_editor.ordinal]
```
Note, that the two items used to populate the array have different content types (`Word`, `Integer`). This seems like a bit of a deviation from current DDLm/dREL practices employed in CIF_CORE.

The `_citation_editor.id` data item seems to currently only be used as a convenient way of aggregating values since it is not explicitly specified as the primary key of the CITATION_EDITOR category (the key is currently a composite one and consists of the `_citation_editor.citation_id`, `_citation_editor.ordinal` pair).

One quick way to resolve the inconsistency could be to update the dREL code to concatenate the two values instead of putting them in an array, e.g.:
```
    _citation_editor.id = _citation_editor.citation_id + "_" + _citation_editor.ordinal
```
The underscore symbol was used as a connector to ensure that unique key values can always be generated (e.g. that concatenation of values 1,55 and 15,1 produce different strings).

Alternatively, the id item could be redefined to have a completely arbitrary value and potentially even become the primary category key.

What approach should be taken?

**Comment by jamesrhester** [comment]
This is dREL that was overlooked when we removed all such synthetic keys from the DDLm dictionary. The dREL should simply be removed, as we did for all other such cases.
