### ISSUE TITLE
Need new data names?: _atom_site_aniso.beta_11, _22, _33, _12, _13, _23

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/cif_core#354]
I've noticed that in a lot of CIFs from the ICSD, the anisotropic displacement parameters are given in terms of beta.

```
_atom_site_aniso_beta_11
_atom_site_aniso_beta_22
_atom_site_aniso_beta_33
_atom_site_aniso_beta_12
_atom_site_aniso_beta_13
_atom_site_aniso_beta_23
```

These data names don't currently exist. Should they?

For my program to read CIFs, I'm calculating B from beta as, for example, :

```
b_11 = 4.0 * be_11 / square_magnitude(a*)
```
where a* is the reciprocal space vector, and square_magnitude is the square of it's magnitude. I'm assuming I got that equation from [Trueblood et al. Acta Cryst 1996, A52, 770-781](https://doi.org/10.1107/S0108767396005697)). (actually, I think it came from http://pd.chem.ucl.ac.uk/pdnn/refine3/adps.htm)

example
```
#(C) 2022 by FIZ Karlsruhe - Leibniz Institute for Information Infrastructure.  All rights reserved.
data_62667-ICSD
_database_code_ICSD 62667
_audit_creation_date 1988-02-22
_audit_update_record 2012-08-01
_chemical_name_common 'Chromium carbide - tau'
_chemical_formula_structural 'Cr23 C6'
_chemical_formula_sum 'C6 Cr23'
_chemical_name_structure_type Ï„-Carbide#Cr23C6
_exptl_crystal_density_diffrn 6.95
_citation_title

;
Atom distributions in tau carbide phases: Fe and Cr distributions in (Cr23-x
Fex) C6 with x=0, 0.74, 1.70, 4.13, 7.36
;
loop_
_citation_id
_citation_journal_full
_citation_year
_citation_journal_volume
_citation_page_first
_citation_page_last
_citation_journal_id_ASTM
primary 'Acta Crystallographica, Section B: Structural Science' 1987 43 230 238
ASBSDK
loop_
_citation_author_citation_id
_citation_author_name
primary 'Yakel, H.L.jr.'
_cell_length_a 10.6595(4)
_cell_length_b 10.6595(4)
_cell_length_c 10.6595(4)
_cell_angle_alpha 90.
_cell_angle_beta 90.
_cell_angle_gamma 90.
_cell_volume 1211.19
_cell_formula_units_Z 4
_space_group_name_H-M_alt 'F m -3 m'
_space_group_IT_number 225
loop_
_space_group_symop_id
_space_group_symop_operation_xyz
1 'z, y, -x'
#...
192 'x+1/2, y+1/2, z'
loop_
_atom_type_symbol
_atom_type_oxidation_number
Cr0+ 0
C0+ 0
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_symmetry_multiplicity
_atom_site_Wyckoff_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_B_iso_or_equiv
_atom_site_occupancy
Cr1 Cr0+ 4 a 0 0 0 . 1.
Cr2 Cr0+ 8 c 0.25 0.25 0.25 . 1.
Cr3 Cr0+ 32 f 0.38199(2) 0.38199(2) 0.38199(2) . 1.
Cr4 Cr0+ 48 h 0 0.16991(2) 0.16991(2) . 1.
C1 C0+ 24 e 0.2751(3) 0 0 . 1.
loop_
_atom_site_aniso_label
_atom_site_aniso_type_symbol
_atom_site_aniso_beta_11
_atom_site_aniso_beta_22
_atom_site_aniso_beta_33
_atom_site_aniso_beta_12
_atom_site_aniso_beta_13
_atom_site_aniso_beta_23
Cr1 Cr0+ 0.00119(4) 0.00119(4) 0.00119(4) 0 0 0
Cr2 Cr0+ 0.00080(2) 0.00080(2) 0.00080(2) 0 0 0
Cr3 Cr0+ 0.00074(1) 0.00074(1) 0.00074(1) 0.00013(1) 0.00013(1) 0.00013(1)
Cr4 Cr0+ 0.00078(2) 0.00065(1) 0.00065(1) 0 0 0.00007(1)
C1 C0+ 0.00088(9) 0.00088(9) 0.00069(6) 0 0 0
#End of TTdata_62667-ICSD
```

**Comment by vaitkus** [comment]
In the past, the general stance of the IUCr was to prefer U over B for the representation of ADP [1] so I guess the same would be true for β.

I also remember encountering the β values at some point (probably in an old paper) and ended up using rules from the same website for the conversion. I see two potential benefits of adding the beta data items:
* A CIF file could faithfully represent the data provided in the original publication without any loss of precision due to conversion.
* The beta definitions could contain references to the paper/website that detail the conversion to B or even the conversion rules themselves in dREL form.

The definitions should also contain the same disclaimer about U being the preferred representation.

@rowlesmr maybe you have any indication on how prevalent the item is in the ICSD? I scanned the COD and there is only a single CIF file that contains the `_atom_site_aniso_beta_11` items (COD ID [4319054](http://www.crystallography.net/cod/4319054.html)).

[1] https://github.com/COMCIFS/cif_core/blob/ef15585b613be740af74f7f3424e6b69d90fb3df/templ_attr.cif#L566

**Comment by rowlesmr** [comment]
I agree with all of those points (I still personally prefer B, as the values are closer to 1, but that is another conversation...:))

.

In our library of 2930 downloaded CIFs, 244 have "_atom_site_aniso_beta_11", which is a goodly proportion.

I can also check with the ICSD on the definition they're using for beta.

**Comment by rowlesmr** [comment]
Reply from the ICSD:
> We enter the temperature factors as they can be found in the publication.
> The conversion on the website* should fit.
> We have 7194 structures with temperature factor beta.


* http://pd.chem.ucl.ac.uk/pdnn/refine3/adps.htm
Their main website says they have "more than 260,000 crystal structures".

I'll start on a PR, and see if I can hack together some drel.

**Comment by rowlesmr** [comment]
> or even the conversion rules themselves in dREL form.

I don't think that works, as the drel would go against the Uij values...

I've added references.

**Comment by vaitkus** [comment]
Thanks for the work, looks good to me. Hopefully COMCIFS will approve this change.

**Comment by jamesrhester** [comment]
I will advise the core DMG group to see if there are any objections.

**Comment by vaitkus** [comment]
The relevant DMG discussion can be found at: https://www.iucr.org/__data/iucr/lists/coredmg/msg00459.html

I took a more thorough look at the `CIF_CORE` dictionary and noticed that there are already a few items that deal with beta, namely, `_atom_site.tensor_beta`, `_cell.convert_uij_to_betaij` and `_model_site.adp_matrix_beta`. However, it seems that these are not generally intended to store data, only to use it in intermediate calculations. Nevertheless, this looks like yet another argument to also permit beta in CIFs.

Also, we should investigate two more dictionary changes as they are very closely related to this issue:
* The `_atom_site.ADP_type` data item may need to be modified to include new enumeration values relating to beta. Not sure if all of the equivalent alternative types for beta should be described (as is done for B: `Bani`, `Biso`, `Bovl`), but at least the `beta_ani` (`\bani`?) enumeration value should be included to relect the addition of the `_atom_site.aniso_beta_*` items.
* The addition of the  `_atom_site.beta_equiv_geom_mean` and `_atom_site.beta_iso_or_equiv` data items may also be required (see the equivalent U/B items for the semantics). Of course, if these items are not currently widely in use, we may choose to skip them for now. @rowlesmr, could you possibly scan your files for the existence of the `_atom_site_beta_equiv_geom_mean` and `_atom_site_beta_iso_or_equiv` items?

**Comment by rowlesmr** [comment]
I shall look.

Naive crystallography question: does `_atom_site_beta_iso_or_equiv` even make sense for non-cubic symmetries?

For B, you have: T = exp{-1/4 sum~i~ [ sum~j~ (B^ij^ h~i~ h~j~ a*~i~ a*~j~) ] }, where the values are modified by the unit cell vectors. 

For \b, the unit cell vector modifications are baked into the values: T = exp{-1 sum~i~ [ sum~j~ (\b^ij^ h~i~ h~j~) ] }

**Comment by rowlesmr** [comment]
`_atom_site_beta_iso_or_equiv` and `_atom_site_beta_equiv_geom_mean`: nothing in my downloaded files, and google has (literally) zero hits on it.

**Comment by jamesrhester** [comment]
No objections from the core group, so we can feel free to add them.
