### ISSUE TITLE
ddl.dic: the _type.contents of the _definition.id data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#36]
The ``_definition.id`` data item is declared as being of type ``Tag`` and as a result is required to start with an underscore symbol ('_'). However, whenever it is used in the Category context, this constraint is violated (i. e. ``ENUMERATION_SET``, ``LOOP``, ``UNITS``).

One of the solutions would be to change the type of the _definition.id to ``name``. Of course, this would restrict the set of allowed characters back to the alphanumeric one, but that would probably be for the best. Dealing with the case insensitive Unicode strings invites a lot of problems and also requires knowledge of the locale that the individual data name conforms to. Consider the following example/

There are two dictionaries **E** and **T**. The **E** dictionary is written in English and **T** dictionary is written in Turkish. The dictionaries have the following data items:
**E**: _data.i  (contains _dotted_ i)
**B**: _data.ı  (contains _dotless_ i)

Both data items fit well in the same data block when they are in lower case:
```
data_lower_case
_data.i 'English value'
_data.ı 'Turkish value'
```
However, in upper case the data names become identical:
```
data_upper_case
_DATA.I 'English value'
_DATA.I 'Turkish value'
```
In addition to that, if we have the data name in upper case, without the knowledge of the locale we simply cannot lower case the data name unambiguously (in the Turkish language the 'I' character lower cases to the 'ı', however in English is lower cases to 'i' ). The German 'ß' character that upper cases to 'SS' is another such example.

The same ambiguity is true not only for the data names, but also for the enumerator values, that have been made case-insensitive in the ``DDLm``.

Has this issue been discussed before?

**Comment by jamesrhester** [comment]
Glad you've spotted that category `_definition.id` do not use underscores.  I think we should revert to not requiring underscores for `_definition.id`, but we need to allow full Unicode at the level of DDLm. Individual dictionaries or organisations can impose further style restrictions, but I think DDLm should be as universal as possible. 
The issue of Unicode normalisation was discussed when putting together the CIF2 syntax standard, and you will see [in the paper](http://journals.iucr.org/j/issues/2016/01/00/aj5269/index.html) that two datanames in a CIF2 block may not be canonical caseless matches of one another. You could infer that separate datanames that were distinct Unicode sequences but canonical caseless matches would never both be defined, as they could never co-occur in a datablock.  However, CIF dictionaries may describe content in many different formats, not just CIF2 format files, so I agree that we need to make this constraint explicit somehow.  We do use capitalisation in datanames (for words derived from people's names, like Fourier), but it is purely for presentation.

So the solution would be to give `_definition.id` the type `Code`, and to also adjust the definition of `Code` to assert that these names must be unique after converting to Unicode canonical caseless form.  I'm not sure that there's an easy way to say this: 'canonically case insensitive'?

**Comment by vaitkus** [comment]
Understood. I still think that the advantages of case insensitive Unicode keys do not outweigh the disadvantages, but I do understand the reasoning.

I support the proposed change for the ``_definition.id``. As for the change in the ``Code`` enumerator, the property of being 'canonically case insensitive' could probably be conveyed with a sentence similar to the following: "Two values are considered identical if their case folded versions are identical as specified in The Unicode Standard, Version 7.0.0, ch. 3, §3.13."

**Comment by jamesrhester** [comment]
I have updated `_definition.id` to be of type `Code`. My previous update today specified the meaning of 'case-insensitive'.

**Comment by vaitkus** [comment]
Thank you for the correction.
