### ISSUE TITLE
Restore the default value to the `_geom_*.site_symmetry_*` items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#362]
During the discussion in #58 it was decided to remove almost all default enumeration values due to them being potentially misleading. However, I would like to propose to restore the default value of `1_555` to the `_geom_*.site_symmetry_*`  data items (e.g. `_geom_angle.site_symmetry_1`, `_geom_hbond.site_symmetry_A`, `_geom_torsion.site_symmetry_3`).

This value indicates that no translation nor symmetry operations were applied and therefore seems like a natural default (it matches the "I know nothing about the symmetry so I will do nothing about the symmetry" approach). Furthemore, data provided in geometry loops is almost always supplementary (i.e. derivable from the coordinates) and thus incorrect assignment of the default does not lead to a serious misinterpretation of the data (or at least to an easily detectable misinterpretation). There are at least two more good reasons to restore the default.

Firstly, there is a well established practice by some popular crystallographic software programs to omit the site symmetry item if all of the looped values are the default value (this practice is probably still ongoing). As a result, the removal of the default values from the dictionary made a large corpus of legacy CIF files a bit more ambiguous when interpreted under DDLm (missing is no longer equal to `1_555`).

Secondly, since the site symmetry items serve as category loop keys and have the `Encode` purpose, the missing key values cannot be automatically elided during the validation process. Having a default values would remediate this.

I understand that the decision on the removal of default values might be final, but I just had to ask before making any sweeping changes to the legacy files (e.g. introducing site symmetry items populated with the default `1_555` values).

**Comment by vaitkus** [comment]
The core CIF group discussion can be found at https://www.iucr.org/__data/iucr/lists/coredmg/msg00460.html.

**Comment by jamesrhester** [comment]
Yes.
