### ISSUE TITLE
Change the purpose of `_diffrn_radiation_wavelength.id` from `Encode` to `Key`

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#364]
Data item `_diffrn_radiation_wavelength.id` serves a category key, but due to the assigned `Encode` purpose cannot be automatically eluded even if the `DIFFRN_RADIATION_WAVELENGTH` loop only contains a single packet. Would it be possible to change the purpose to `Key`, i.e. to declare that this item holds arbitrary key values? The definition of the `_diffrn_radiation_wavelength.id` states that:
```
    Code identifying a radiation used in the diffraction measurements.
    This is linked to _diffrn_refln.wavelength_id and _refln.wavelength_id
``` 
and provides an example of `x2`, but it is unclear to me if it is intended to hold a semantically meaningful value.

COD revision 282212 contains 1139 files with an explicit  `_diffrn_radiation_wavelength.id` data item. The full summary of all explicit values is provided in the attached file ([diffrn-radiation-wavelength-values.txt](https://github.com/COMCIFS/cif_core/files/11143113/diffrn-radiation-wavelength-values.txt)) while an excerpt of the most numerous values is provided below:

| Value       | Frequency |
| ------------- | ------------- |
| all | 383  |
| 1 | 232 |
| 2 | 223 |
| x-ray | 17 |
| 0.71073 | 8  |
| ... | ... |
| sba26masq | 2 |
| p91tas | 2 |
| ... | ... |

The rest of the over 460 values all mostly resemble some kind of unique identifiers similar to the ones provided in the table (`sba26masq`, `ill002c`, etc.). Not sure if this clarifies the intended semantics of the item.

Note, that this change would also affect the purposes of `_diffrn_refln.wavelength_id` and `_refln.wavelength_id`.

**Comment by jamesrhester** [comment]
I agree that this should be `Key`.
