### ISSUE TITLE
ddl.dic: the _type.contents of the _dictionary_valid.attributes data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#37]
The ``_dictionary_valid.attributes`` data item is declared as being of type ``Name``. This limits the allowed character set to the alphanumeric one with the underscore symbol included (``[a-zA-Z0-9_]``). However, some of the ``_dictionary_valid.attributes`` do contain the ``'.'`` symbol as well (i. e. ``_dictionary.title``, ``_dictionary.class``, etc.). The definition of the ``Name`` type should probably not be changed since the exclusions of the '.' symbol seems to be intentional (data items of this type are referenced in ``dREL`` scripts).

I propose changing the ``_type.contents`` value from ``Name`` to ``Tag``. This would extend the allowed character set to the Unicode one, but it should not be a problem, since data items and categories are already referenced by their ``_definition.id`` and not the ``<_name.category_id>.<_name.object_id>`` construct (i.e. ``ALIAS`` vs. ``ATTRIBUTES.ALIAS``); the ``_definition.id`` data item does allow the Unicode set.

It seems, that the newly added ``_definition.replaced_by`` data item suffers from the same problem as well.

**Comment by jamesrhester** [comment]
I have changed the type to `Code` as categories can also appear in `_dictionary_valid.attributes`. `_definition.replaced_by` has also been changed to `Tag` as the contents will always be a data name, never a category so the more restrictive type is appropriate.

**Comment by vaitkus** [comment]
Thank you for the correction.
