### ISSUE TITLE
Create a dictionary_author category

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#377]
The dictionaries represent quite a large scholarly effort, and the authors/guilty parties should be acknowledged. I suggest that a dictionary_author category would provide a loop over names and orcid ids, and appear after the dictionary_audit information.

Alternatively, the authors of a particular data name definition could be acknowledged, but I think that is too granular and is in any case provided by the Git history.

**Comment by rowlesmr** [comment]
I think the alternate is a little too specific. Yes, probably one person wrote a definition. At what point does a maintainer get their name added? Sounds a little too hard to write policy around.

Whole-scale effort is much easier to account for. Just fix typos? You did the entire set of dictionaries, on the list. Ensure consistency within and between the dictionaries, on the list. Write definitions, on the list. and so on and so fifth.
