### ISSUE TITLE
ddl.dic: some enumeration values contain whitespace characters

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#38]
Some enumeration values violate the ``Code`` data type constraints by containing a whitespace symbol:
1) ``ddl.dic``: the ``_audit.schema`` data item contains the enumeration value ``'Space group tables'``. Even stranger, the _type.contents of the ``_audit.schema`` data item is ``Text`` even though the save frame contains enumerator values;
2) ``templ_enum``: several save blocks that involve space groups (``_H_M_ref``, ``_ref_set``) contain
numerous enumeration values with whitespace symbols (``'P 1'``, ``'P -1'``, ...).

I propose three possible approaches:
1) Replace the spaces with underscores. This approach seems to be the smallest amount of work and risk of breaking anything else);
2) Change the ``_enumeration_set.state`` data item data type from ``Code`` to `` Implied``. However, I would argue against this approach since it would make  the usage of enumeration values highly irregular (sometimes they would be case sensitive and sometimes not, etc.);
3) Modify the ``Code`` data type to allow the space (``' '``) symbol. The text would be more readable in certain cases (e.g. space group symbols), but I'm unsure if it won't break anything else.

What do you think?

**Comment by jamesrhester** [comment]
We are not able to change the enumerated state list for the space group names at this stage, given that they were inherited from the original CIF core dictionary. 

Alternative 2 is not so bad, as there are currently two places that the type of an enumerated_set.state item is given, one in the definition of the item, and another in the definition of  `enumerated_set.state`.  By using `Implied` for `_enumerated_set.state` we remove the potential for contradiction, and handling of enumerated states is guided by the type of the definition it appears in. Is this really any more irregular than every definition having a potentially different type?

As far as alternative (3) goes, clearly whitespace has to be acceptable in enumerated state values, therefore the type of enumerated_set.state would be changed to Text.  We can also simply create a new type that is case-insensitive Text.

**Comment by vaitkus** [comment]
**Alternative 2**. I am a bit hesitant towards this alternative since different data types have different comparison rules. Not only does this add an additional level of complexity, but also introduces some ambiguity. For example, it is not completely clear how enumerator value of the ``Real`` data type should be compared (are '0.5', '.5' and '0.500' the same value?).

**Alternative 3**. Actually, I would even prefer for the`` _enumerated_set.state`` data type to be changed to ``Text`` since enumerator values would return to being case sensitive again (as they were in ``DDL1``). Of course, if the loss of case insensitivity is undesirable the addition of a case insensitive 'Text' data type seems reasonable.

**Comment by jamesrhester** [comment]
OK, let's go with Text for the type of `_enumerated_set.state`. We could also explore the idea of having the `_type.contents` of the data name definition that contains `_enumerated_set.state` being an optional further restriction on `Text`, i.e. a subset of the text sequences allowed by `Text` (but never with numeric interpretation).

**Comment by jamesrhester** [comment]
I have updated cif_core.dic to have `_type.contents` of `Text` for all definitions containing enumerations.  This is not entirely satisfactory, as it is clear that case and whitespace is significant for only a small number of them. It would be useful to have an interpretation of `_type.contents` that allows the dictionary definition to further restrict the type of the defined item.  We can simply say that all non-numerical string types are subsets of 'Text', which allows 'Code' and 'Tag' and 'Name' among others.

**Comment by vaitkus** [comment]
I understand the way this would work, but is it really worth it?
1) Type validation of the enumerator values is really only important in the dictionary validation context.
In the actual CIF files that conform to the dictionary enumeration values are usually simply matched against the predefined list and not interpreted in any way;
2) Allowing case insensitivity to some enumeration values, but not to others seems a bit inconsistent. And inconsistencies is a known trap for lazy software developers;
3) As far as the character sets go, the creator of the dictionary can simply choose to restrict the enumeration values to his chosen ones without explicitly stating it. 

I will be perfectly happy with whichever solution you choose, but the current proposal seems like a bit of an over regulation. Maybe there's a scenario in which these subsets would prove highly useful that I am simply missing?

**Comment by jamesrhester** [comment]
On balance I agree with @vaitkus 's observations.  The main advantage of e.g. having `_type.contents` of a definition containing enumerated states be `Code` would be to remove the necessity of listing all case variants; but this would then open the possibility that programmers would match only on the state strings, and not realise that sometimes they need to do a caseless match. I agree that we should leave it as is.
