### ISSUE TITLE
Potentially incorrect `_atom_type.radius_contact` method type

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#382]
The `_atom_type.radius_contact` method provides the following Evaluation method:
```
_atom_type.radius_contact =  _atom_type.radius_bond + 1.25
```
However, the provided code seems to calculate a default value rather than the single "true" value. Maybe it is better rewritten as a Definition method, e.g.:
```
_enumeration.default = _atom_type.radius_bond + 1.25
```

**Comment by jamesrhester** [comment]
I agree. `1.25` seems arbitrary.
