### ISSUE TITLE
templ_enum.cif: the neutron scattering length of V is more precise than V{2,3,5}+

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#383]
The `length_neutron` same frame list the value of V as -0.3824 while the V2+, V3+ and V5+ are assigned the -0.382. This is a bit unusual since in all other cases the atom and ions of a specific element are all assigned the same value (e.g. Al/Al3+, Si/Si4+).

Should the value of V, or the values of V{2,3,5}+ be changed?

**Comment by jamesrhester** [comment]
Neutron scattering length is not dependent on charge, so these numbers should all be identical.
