### ISSUE TITLE
Is there a way of dynamically extending the list of measurement units given in the DDLm reference dictionary?

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#385]
The DDLm language was successfully applied outside the field of crystallography to create dictionaries that describe Raman spectroscopy experiments (see [1]). However, during the development of these dictionaries several new units of measurement which are not defined in the DDLm reference dictionary, were introduced (e.g. `arbitrary_units`, `lines_per_millimetre`).

I was wondering if there is a way of dynamically adding these units in an instance dictionary or would this necessarily require the modification of the DDLm dictionary itself, e.g. by using a patched version of the `templ_enum.cif` file?

[1] https://github.com/cod-developers/cif_raman/blob/master/dictionaries/cif_raman_0.3.3.dic

**Comment by jamesrhester** [comment]
There is currently no way to do this dynamically, given that the units list forms part of the upper ontology by being imported into the dictionary describing the DDLm language. However, the developers of the Raman spectroscopy dictionary are welcome to submit a PR to `templ_enum.cif`. Part of the idea of putting the units into a separate file in this way is to make it easier to expand the list.

**Comment by vaitkus** [comment]
Thank you for the clarification. I will relay the issue to the developers of the Raman spectroscopy dictionary.
