### ISSUE TITLE
question on audit_author and automation

### ISSUE THREAD

**Issue by pameyer** [COMCIFS/cif_core#388]
Apologies in advance if a github issues isn't the appropriate place for this type of feedback or question.

With the guidance to identify authors by opaque identifier, instead of a first name/last name combination; has there been any consideration for cases where the author of a deposition may be a combination of instrumentation and software (in other words, not a person)?

My reading of the specification is that this isn't something that is explicitly supported; but that there also isn't anything that would preclude doing so in a non-core dictionary in the future - does this seem accurate?

**Comment by jamesrhester** [comment]
This is the exact right place for this to be raised.

I agree that machine authors are not explicitly excluded, and I'm pretty sure that this issue has never been discussed. Datanames describing the software that assisted the authors are provided in the `COMPUTING` category.

A number of issues I can see:
1. How to identify software as an author (name, version, DOI, etc.)
2. When software can be considered an author rather than something that assisted a human.

**Comment by pameyer** [comment]
@jamesrhester - thank you for the conformation on this not something explicitly excluded in the schema, and identifying some potential issues that would need to be addressed.

1. For identifying software as an author, it might be possible to build on work being done for making software citable.  I wouldn't be surprised if it would need to be extended further, to make the distinction between particular instances/installations of software more explicit.

2. There seems to be increased general discussion lately about when software could be considered an author vs tool to assist a human author, and it seems to be relatively far from a solved problem.  For `audit_author` and deposition metadata in general, my (potentially naive) thinking had been that "if the agent (human, software/instrumentation, or otherwise) has its own set of credentials in the repository for where the depositon is happening, it counts as a deposition author".  Of course, this is moving the problem somewhere else (to the repository operators/administrators/curators) rather than answering the question.

**Comment by jamesrhester** [comment]
I think in any case having opaque author identifiers leaves the option open for authors who do not have first/last names to be included, once resolution is reached in the community. Something as simple as a link to a software citation should fit easily into our current setup.
