### ISSUE TITLE
ddl.dic: clarification on the 'Symop' data type

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#39]
The 'Symop' data type was extensively discussed in the #32. The following definition of the data type was accepted:  ``a string composed of an integer followed by an underscore and 3 or more digits``. However, the following examples are given in the ``save_site_symmetry`` save frame of the ``templ_attr.cif`` file:
```
loop_
_description_example.case
_description_example.detail
'4'           '4th symmetry operation applied'
'7_645'       '7th symm. posn.; +a on x; -b on y'
'.'           'no symmetry or translation to site'
```
The value '4' clearly does not fit the current formal type format (even if the ``'_555'`` part can be implied). Is the example wrong, or should the ``'_\d\d\d'`` part be treated as optional (in that case, the type definition should reflect that)?

Also, the example value `'.'` should be unquoted in order for it to be treated as a special CIF value.

**Comment by jamesrhester** [comment]
DDL1 allowed missing symmetry translations so we should follow suit. I have corrected the type in a recent update to ddl.dic. The quotes from the example have also been removed.

**Comment by vaitkus** [comment]
Thank you for the correction.
