### ISSUE TITLE
templ_enum.cif: add `_units.code` to save frames

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#391]
It would be useful to have the units of measure in the same save frame as the enumerated values since the same save frame may potentially be imported by multiple definitions. This is probably most useful in the `atomic_mass`, `radius_bond` and `length_neutron` save frames (and potentially in `electron_count` to make it clear that is unitless and not measured in electrons).

The `_units.code` can still be retained in the importing save frames and simply ignored or replaced depending on the import mode.

**Comment by jamesrhester** [comment]
I don't understand the suggestion. Perhaps you could give an example?

**Comment by vaitkus** [comment]
@jamesrhester sorry for being unclear.

I suggest adding the `_units.code` attribute directly to some of the save frames in the `templ_enum.cif` file. An example of this can be seen in PR #396 where femtometres are explicitly added as units in the `length_neutron` save frame.

**Comment by jamesrhester** [comment]
Yes, I see now. I agree that this is a good idea.

**Comment by rowlesmr** [comment]
Questions re units.

Shouldn't all the `b` coefficients for Cromer-Mann have units of `angstrom_squared`?

![image](https://github.com/COMCIFS/cif_core/assets/14921460/99884578-ede9-4e75-bd52-5d593080f2f8)



Shouldn't the Fox coefficients all have various powers of angstroms as their units?

![image](https://github.com/COMCIFS/cif_core/assets/14921460/49ac6793-2a64-41f5-996c-7669271712cd)
