### ISSUE TITLE
cif_core.dic: incorrect _exptl_crystal.colour usage example

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#40]
The ``_description_example.case`` data item is defined as a list of three code elements, however, the definition contains the following example:
```
loop_
  _description_example.case
         '[transluscent, pale, green]' 
```
Since the example should contain a list and not a string (as the ``Implied`` type suggests), it should probably be changed to:
```
loop_
  _description_example.case
         [transluscent pale green] 
```

However, the ``_description_example.case`` data item is defined as having the ``Single`` type container, so
a list is not allowed in this context. This is not the only example of this kind of issue. For example, the definition of the ``_atom_site_displace_special_func.sawtooth`` data item in the ``cif_ms.dic`` dictionary contains the following enumeration default:
```
_enumeration.default         [0.0  0.0  0.0]
``` 
However, the ``_enumeration.default`` data item is also defined as having the ``Single`` type container and as a result the list is not allowed in this context. Maybe an additional ``Implied`` container type could be introduced or the issue could eventually be corrected by the means discussed in #34?

On a related note, the enumerator value ``transluscent`` seems to be misspelt in this example, as well as in the definition of the ``_exptl_crystal_appearance.general`` data item.

**Comment by jamesrhester** [comment]
Adding 'Implied' to the list of possible containers would be the simplest solution. There may be a satisfying solution involving dREL and 'Definition' methods, in which a dREL method is invoked to calculate the value of an attribute (such as _description_example.case) on a per-definition basis, but this hasn't been developed yet. Using 'Implied' as a place-holder would be sufficient for now, I think.

**Comment by jamesrhester** [comment]
The latest commit of ddl.dic contains this update.
