### ISSUE TITLE
cif_pow_multiphase.dic: unrecognised data item '_name.linked_object_id'

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#41]
The ``cif_pow_multiphase.dic`` dictionary contains an unrecognised data item ``'_name.linked_object_id'``. Most likely, it is an misspelt version of the ``_name.linked_item_id`` data item.

**Comment by jamesrhester** [comment]
It is indeed a misspelt version. I have updated the file.

**Comment by vaitkus** [comment]
Thank you for the correction.
