### ISSUE TITLE
drel: interpretation of the geom_*() functions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#418]
Functions `geom_angle(...)`, `geom_bond(...)`, `geom_contact(...)`, `geom_torsion(...)` are called in dREL code, but do not seem to be defined anywhere. Are these considered builtin functions or are they simply not defined yet?

**Comment by jamesrhester** [comment]
These are "dotted assignments" which are not documented in the original dREL paper but are in the forthcoming Vol G chapter on dREL. See `dotlist_assign` in the [annotated grammar](https://github.com/COMCIFS/dREL/blob/master/annotated-grammar.rst).
