### ISSUE TITLE
Add example CIF files that illustrate the usage of the `ATOM_ANALYTICAL` category

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#425]
As discussed in PR #313 it would be useful to have a full example of how the `ATOM_ANALYTICAL` category could be used in a CIF file (see https://github.com/COMCIFS/cif_core/pull/313#pullrequestreview-1196636679).

**Comment by rowlesmr** [comment]
I'm putting one together. I made it in v1.1 with my TOPAS CIF making stuff and manually altered it to v2.0. So it should work with no errors at all ;).

**Comment by rowlesmr** [comment]
An abridged one:
