### ISSUE TITLE
Missing data name in multiple dictionaries

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#43]
When compared to their ``DDL1`` counterparts multiple ``DDLm`` dictionaries seem to be missing some of the data names. I have also surveyed the COD (svn revision **197917**) for the usage of these data names -- the number of occurrences will be displayed in parenthesis.

1.  **cif_core.dic**
 The DDLm cif_core.dic when compared to the DDL1 cif_core.dic seems to be
missing the following data names:
``_audit_block_doi`` (1323)
``_citation_doi`` (213)
``_citation_publisher`` (0)
``_database_dataset_doi`` (0)
``_publ_contact_author_id_orcid`` (0)
``_publ_author_id_orcid`` (0)
``_diffrn_refln_crystal_id`` (1)
``_refln_crystal_id`` (0)
``_space_group_id`` (11)
``_space_group_symop_sg_id`` (0)
``_symmetry_Int_Tables_number`` (38276)
``_symmetry_equiv_pos_site_id`` (14566)

1.1. The ``_audit_block_doi``, ``_citation_doi``, ``_citation_publisher``, ``_database_dataset_doi``, ``_publ_contact_author_id_orcid`` and ``_publ_author_id_orcid`` data items are not defined in the ``DDLm`` dictionary at all.

1.2. The ``_diffrn_refln_crystal_id`` and ``_refln_crystal_id`` data items are also not defined in the DDLm dictionary even though the related data item ``_exptl_crystal_id`` is defined. Maybe these two data names could become aliases for the ``_exptl_crystal_id`` data name? The COD currently has 1 entry that contains the ``_diffrn_refln_crystal_id`` data name, no entries that contain the ``_refln_crystal_id`` and 610 entries that contain the ``_exptl_crystal_id``.

1.3. I assume that the ``_space_group_id`` and ``_space_group_symop_sg_id`` data items were purposely removed due to space group information no longer being looped in the ``DDLm``. The COD currently has 11 entries that contain the ``_space_group_id`` data item and 0 entries that contain the ``_space_group_symop_sg_id``. However, in all cases the data item seems to be misused (used in a separate loop from the rest of the data or given the same value as the ``_space_group_IT_number``
data item) and as a result the data items will most likely be removed from these files. I would lean towards removing these data items in the DDL1 legacy dictionary as well (after disallowing the looped space group information). Do you agree?

1.4. The ``_symmetry_Int_Tables_number`` and ``_symmetry_equiv_pos_site_id`` data names are not listed as aliases for the data items ``_space_group.IT_number`` and ``_space_group_symop.id`` respectively, but their doted counterparts (``_symmetry.Int_Tables_number`` and ``_symmetry_equiv.pos_site_id``) are. I recommend adding the aforementioned data names as aliases. I have included this small correction among others in my pull request #30.

2. **cif_ms.dic**
When compared to the DDL1 cif_ms.dic the DDLm cif_ms.dic seems to be missing the following data names:
``_refln_index_m_1`` (20)
``_refln_index_m_2`` (5)
``_refln_index_m_3``
``_refln_index_m_4``
``_refln_index_m_5``
``_refln_index_m_6``
``_refln_index_m_7``
``_refln_index_m_8``

3. **cif_pow.dic** (``cif_pd.dic``)
When compared to the DDL1 cif_pd.dic the DDLm cif_pow.dic  seems to be missing the following data names:
``_pd_spec_size_equat`` (523)
``_pd_spec_size_thick`` (405)
``_pd_instr_monochr_pre_spec`` (8)
``_pd_instr_monochr_post_spec`` (6)

3.1. The ``_pd_spec_size_equat`` and ``_pd_spec_size_thick`` data items are not defined
at all.

3.2. The ``_pd_instr.monochr_pre_spec`` and ``_pd_instr.monochr_post_spec`` data items
are defined, but are missing the ``_pd_instr_monochr_pre_spec`` and
``_pd_instr_monochr_post_spec`` aliases (they do have ``_pd_instr_monochr_pre/spec``
and ``_pd_instr_monochr_post/spec`` aliases instead). I recommend adding the aforementioned data names as aliases. I have included this small correction among others in my pull request #30.

4. **cif_rstr.dic** (``cif_core_restraints.dic``)
When compared to the DDL1 cif_pd.dic the DDLm cif_pow.dic  seems to be missing the following data name:
``_restr_equal_angle_detail`` (0)

4.1.  In this case the error seems to stem from the DDL1 dictionary (cif_core_restraints.dic) and not the DDLm one (cif_rstr.dic). The DDL1 dictionary contains a typo in the name of the data item -- it is written as '_restr_equal_angle_detail' even though the related data block is named '_restr_equal_angle_details'.

The survey of the COD revealed that neither '_restr_equal_angle_detail' nor
'_restr_equal_angle_details' data name was used at all so I think it is
safe to correct the legacy DDL1 dictionary and leave the DDLm one as is.
Do you agree?

5. Finally, some data items contain aliases that are identical to their ``_definition.id``. Is it a bug or a feature?

**Comment by jamesrhester** [comment]
1.1 These datanames were added to DDL1 core after the development of the DDLm core began. Their equivalents should be added to the DDLm version
1.2 and 1.3. These datanames were removed as part of the removal of improper loops in DDL1. This is discussed in detail in the [audit.schema specification](https://github.com/COMCIFS/comcifs.github.io/blob/master/looping_proposal.md)
1.4 I think the suggested fixes to the aliases are correct
2 (cif_ms.dic) The DDLm version of this dictionary is currently under review by the original author.  Once an updated version is ready this will be checked.
3.1 These pd items seem to have been inadvertently left out and should be returned.
3.2 The all underscore versions are in theory not valid aliases as these items were never defined in the DDL1 dictionary. It is interesting that they appear in pd files in the COD. I agree that we can include these as aliases in the DDLm version although I wouldn't want to set a precedent.
4.1 I agree that it appears to be a typo, which is in danger of being enshrined as canon, as the draft version of the constraints/restraints dictionary Vol G chapter also uses 'detail' in this one constraint, whereas all of the other types of constraints use 'details'.  I will advise the author, and let him know that no deposited files are using this dataname yet.
5. This is a bug that I think I introduced when using an earlier version of my STAR2->CIF2 conversion software.

**Comment by vaitkus** [comment]
Thank you for the quick reply.

1.2, 1.3. The specification seems useful, thank you for the reference.

3.2. I feel a bit confused about this comment. The ``_pd_instr_monochr_pre_spec`` and ``_pd_instr_monochr_post_spec`` seem to be defined in the ``data_pd_instr_monochr_`` data block of the ``cif_pd.dic`` ``DDL1`` dictionary (ftp://ftp.iucr.org/pub/cif_pd.dic). Maybe it was an error in the ``DDL1`` dictionary?

5. I have removed the aliases that match the _definition.id an issued a pull request #44.

**Comment by jamesrhester** [comment]
Regardng the post/spec and post_spec items: my mistake, I had confused these with the spec/detc type items. The pre/spec and post/spec forms should be removed, as they never existed, and the all underscore forms are the correct aliases.  I have fixed these in the repository.

**Comment by jamesrhester** [comment]
The most recent commit of the core contains the missing datanames identified in point 1.1

**Comment by vaitkus** [comment]
Thank you for the fix. However, it seems that the missing data names referred to in 3.1 (``_pd_spec_size_equat`` and ``_pd_spec_size_thick`) were not returned to the **cif_pow.dic** dictionary. Is the dictionary still under review?

**Comment by jamesrhester** [comment]
This was an oversight, the latest version of cif_pow.dic should now be correct. Please check and I will close if OK.

**Comment by vaitkus** [comment]
Thank you, the issue seems to be resolved.
