### ISSUE TITLE
Incorrect description of '_audit.creation_date' in cif_core.dic

### ISSUE THREAD

**Issue by merkys** [COMCIFS/cif_core#45]
Description of ``_audit.creation_date`` in cif_core.dic presents the format of date as ``dd-mm-yyyy`` while ``_type.contents`` of ``_audit.creation_date`` is ``Date`` which mandates the ISO standard date format.

**Comment by jamesrhester** [comment]
This is clearly an error in the cif_core.dic definition, as the example within the definition is in `yyyy-mm-dd` format. I will fix in next commit.
