### ISSUE TITLE
_definition.class for AUDIT_CONFORM should be 'Loop' instead of 'Set'

### ISSUE THREAD

**Issue by merkys** [COMCIFS/cif_core#46]
According to cif_core v2.4.5, ``_audit_conform_*`` tags may appear in a loop (according to http://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iaudit_conform_dict_name.html), while such use is effectively forbidden in v3.0.07 (``_definition.class`` of AUDIT_CONFORM is ``Set``, not ``Loop``).

**Comment by jamesrhester** [comment]
Indeed  `_audit_conform` should be a Loop category. This is fixed in my latest commit.
