### ISSUE TITLE
Inconsistency in `DIFFRN_RADIATION`: `_definition.class` vs `_definition.text`.

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/cif_core#463]
`DIFFRN_RADIATION` is a `Set` category. It's description says 
> Items may be looped to identify and assign weights to distinct wavelength components from a polychromatic beam.

I think that that functionality has been delegated to `DIFFRN_RADIATION_WAVELENGTH`. Shoudl the description be updated?

**Comment by vaitkus** [comment]
Related to issue #168.
