### ISSUE TITLE
Should data names deprecated in DDL1 be deprecated in DDLm?

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#477]
The DDL1 version of the `CIF_CORE` dictionary contains many deprecated data items. There were two main types of deprecation:
A) Deprecation due to semantics (`_atom_site_refinement_flags`, `_symmetry_cell_setting`).
B) Deprecation to discourage the use of certain potentially misleading terms (e.g. `_refine_ls_goodness_of_fit_obs` was replaced with `_refine_ls_goodness_of_fit_gt`).

While data items affected by type A deprecation seem to be properly represented in the DDLm version of the dictionary, data names affected by type B deprecation were converted to regular aliases without any notice that their usage should be avoided. Note, that the DDLm reference dictionary does have the `_alias.deprecation_date` attribute to denote just such alias, but currently it is no widely used. Should it?

**Comment by jamesrhester** [comment]
Yes, I think we should deprecate type B items as well.
