### ISSUE TITLE
cif_core.dic: potentially incorrect '_atom_site.refinement_flags_occupancy' enumerator values

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#48]
The enumerator values of the ``_atom_site.refinement_flags_occupancy`` data item differ greatly between the ``DDL1`` and ``DDLm`` versions of the dictionary:

``DDL1`` version:
```
loop_
_enumeration
_enumeration_detail
.     'no constraints on site-occupancy parameters'
P     'site-occupancy constraint'
```
``DDLm`` version:
```
loop_
_enumeration_set.state
_enumeration_set.detail
.    'no constraints on atomic displacement parameters'          
T    'special-position constraints on atomic displacement parameters'     
U    'Uiso or Uij restraint (rigid bond)'    
TU   'both constraints applied' 
```

I have a hunch that the values in the ``DDLm`` version got mixed up with the enumeration values of the ``_atom_site.refinement_flags_occupancy`` data item.

**Comment by jamesrhester** [comment]
Your hunch is no doubt correct. The enumerated states have been returned to their original values in my latest commit.

**Comment by vaitkus** [comment]
Thank you for the correction.
