### ISSUE TITLE
cif_core.dic: enumerator list of _atom_sites.solution_hydrogens data item differs between DDL1 and DDLm versions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#49]
The enumerator list of the ``_atom_sites.solution_hydrogens`` data item differs a bit in the ``DDL1`` and ``DDLm`` version. For some reason, the ``mixed`` value is present in the ``DDL1`` version, but not in the ``DDLm`` one. Is this intentional?

**Comment by merkys** [comment]
Value ``mixed`` in ``DDL1`` stands for a combination of ``geom`` and ``difmap``. Possibly ``mixed`` could be removed from ``DDLm`` in favour of explicit composite values like ``[ geom diffmap ]``.

**Comment by vaitkus** [comment]
It potentially could, but I would advise against it. First, it would require to change the ``_atom_sites.solution_hydrogens`` definition in the ``DDLm`` dictionary to allow composite values. Secondly, the ``mixed`` value is already widely used (10721 instances of the value in the COD revision 201200) so simply removing the enumerator would leave the files non-conforming to the dictionary.

**Comment by merkys** [comment]
Agree. Let's make it as backwards compatible as possible.

**Comment by jamesrhester** [comment]
'mixed' will be returned in the next commit.

**Comment by vaitkus** [comment]
Thank you for the correction.
