### ISSUE TITLE
Data item `_publ_contact_author` should not be an alias of `_publ_contact_author_name`

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#498]
In the DDL1 version of the dictionary, the `_publ_contact_author` data item was originally intended to hold the full name and the address of the contact author in a single field. Although it was never formally deprecated, a disclaimer that recommends using the `_publ_contact_author_name` and `_publ_contact_author_address` data items instead of this item was later on added.

However, during the migration to DDLm the `_publ_contact_author` data name was redefined as an alias of `_publ_contact_author_name`. While this is not a serious issue, it does trigger validation errors when checking legacy CIF files (sometimes both the `_publ_contact_author` and `_publ_contact_author_name` data items are present, but with differing values).

I propose to split the `_publ_contact_author` data name into a separate definition and then formally deprecate it. Does this sound ok?

**Comment by jamesrhester** [comment]
I agree that this is a reasonable course of action.

**Comment by nautolycus** [comment]
I also have no objection.
