### ISSUE TITLE
cif_core.dic: enumerator list of the _exptl_crystal_appearance.general (aliased as _exptl_crystal.colour_lustre) data item differs between DDL1 and DDLm versions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#51]
When compared to the DDL1 version of the dictionary the DDLm one seems to be missing the following enumerator values of the _exptl_crystal.colour_lustre data item: ``dull``, ``clear``.

When compared to the DDLm version of the dictionary the DDL1 one seems to be missing the following enumerator values of the _exptl_crystal.colour_lustre data item: ``transluscent``, ``lustrous``, ``transparent``, ``opaque``, ``.``.

If possible, I would propose merging the enumerator value sets from DDL1 and DDLm for compatibility purposes (it could be noted that values ``dull`` and ``clear`` are synonyms of ``opaque`` and ``transparent`` accordingly and should generally not be used). In the COD revisions 201200 the value ``dull`` is used 75 times and the values ``clear`` is used 2641 times.

In addition to that, the enumerator value ``transluscent`` seems to be misspelt.

**Comment by jamesrhester** [comment]
I agree with the suggestion to merge the two lists. I am not sure that the terms indicated are exact synonyms (perhaps `clear` could be either `transparent` or `translucent` if your only choice is `clear` or `dull`), so I think it would be better to simply suggest that `dull` and `clear` should no longer be used. Please update the DDL1 legacy dictionary accordingly. My next commit of cif_core will include these changes.

**Comment by vaitkus** [comment]
Missing values as well as the disclaimer about ``dull`` and ``clear`` were added to DDL1.
