### ISSUE TITLE
cif_core.dic: enumerator list of the _geom_torsion.publ_flag data item differs between DDL1 and DDLm versions 

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#53]
The ``_geom_torsion.publ_flag`` data item seems to have lost its short form enumerator values "y" and "n" (short for "yes" and "no" respectively) while undergoing the conversion from ``DDL1`` to ``DDLm``,

In addition to that, the ``_reflns.apply_dispersion_to_Fcalc`` data items is also missing the short form enumerator values even though technically this is not an error since the data item was not previously defined in the ``DDL1`` dictionary. However, for consistency sake I would recommend adding these values since they are present in all data items containing the yes/no enumerators,

The implementation of these changes can be seen in the pull request #52.

**Comment by jamesrhester** [comment]
Pull request merged.
