### ISSUE TITLE
cif_core.dic: definition of refln.d_spacing

### ISSUE THREAD

**Issue by publcif** [COMCIFS/cif_core#54]
Is the definition

_refln.d_spacing = 2. / _refln.sin_theta_over_lambda

correct, i.e. Braggs law n\l = 2d sin\q with n=4 ?

**Comment by jamesrhester** [comment]
Clearly a mistake, it should be 1/ (2 * _refln.sin_theta_over_lambda). This will be fixed in my next commit.
