### ISSUE TITLE
ddl.dic: proposal for the expansion of the 'Date' type definition

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#55]
Currently, the ``Date`` data format is defined as "``ISO date format yyyy-mm-dd``". However, for some applications a more precise timestamp is needed. Would it be possible to extend this data format to the full (or at least wider) scope of formats defined in the ISO 8601 specification? I.e.:
``2017-10-19``
``2017-10-19T16:09:58+00:00``
``2017-10-19T16:09:58Z``

This change would leave the older values valid whilst providing a more diverse use of the data type. What do you think?

**Comment by merkys** [comment]
I would rather suggest completely compatible switching from ISO 8601 to [RFC3339](https://tools.ietf.org/html/rfc3339) ``date-time`` as ISO 8601 is closed standard and has some features that we do not need (date without year, ordinal date etc) whereas RFC3339 is open and even described in augmented Backus–Naur form.

**Comment by vaitkus** [comment]
That seems even better.

**Comment by jamesrhester** [comment]
I think that this is a reasonable suggestion, however we must consider how currently-deployed software might react to a value that is longer than originally expected and does not precisely match the original format.  Unlike the fractions in #56 , there is a chance that the impact would be fairly minor, but we should still canvas the wider community to find out.

**Comment by jamesrhester** [comment]
After a bit more thought I think we should just add a separate DateTime type to the list of types. Some data names already use essentially DateTime type, for example _pd_meas.datetime_initiated. By adding a new type we also avoid any chance of rendering deployed software incorrect.  We can also deprecate Date type to send a signal to programmers to expect a full date-time string.

**Comment by vaitkus** [comment]
An additional data type works for me.

**Comment by merkys** [comment]
I am also in favor of smooth transition.

**Comment by merkys** [comment]
@vaitkus and I have noticed that RFC3339's definition of timestamp (``date-time`` production of their ABNF) seems to refer to a timestamp with both date and time parts, therefore, ``2017-10-19`` is not actually a RFC3339 timestamp proper. Nevertheless, I suggest explicitly putting this in the definition of CIF DateTime, something along the lines:
```
    _enumeration_set.state
    _enumeration_set.detail
    ...
    DateTime 'date-time or full-date productions of RFC3339 ABNF'
```

**Comment by jamesrhester** [comment]
I am in the process of reorienting the DDLm dictionary to be syntax-agnostic. From this standpoint, if a format wishes to encode dates as Julian days or number of days since the epoch as a binary integer, in principle it can and remain conformant to the dictionary. Clearly CIF format will stick to a single approach, which would be as you suggest.  This means that we should produce a very short standards document providing the required syntax for each data type. For now I will update ddl.dic with the DateTime type, without specifying syntax.

**Comment by vaitkus** [comment]
Great, thank You.
