### ISSUE TITLE
ddl.dic: proposal for the expansion of the 'Real' type definition

### ISSUE THREAD

**Issue by merkys** [COMCIFS/cif_core#56]
I suggest expanding the definition of ``Real`` to allow fractional numbers by allowing to append ``/[1-9][0-9]*`` to currently allowed ``Real`` numbers. Such expansion would allow to avoid rounding problems such as conversion of ``1/3`` to ``0.333333``, what is somewhat a loss of information – it is not unusual for papers to report coordinates/occupancies in fractional numbers.

Of course such change would require all reading programs to be aware of possible fractional numbers. However, specialized libraries already exist for [Perl](http://search.cpan.org/~davecross/Number-Fraction-2.00/lib/Number/Fraction.pm), [Python](https://docs.python.org/2/library/fractions.html) and [Java](http://commons.apache.org/proper/commons-math/userguide/fraction.html) languages.

**Comment by jamesrhester** [comment]
Unfortunately such a change would render currently deployed CIF-reading software unable to correctly interpret data values that used this new convention, so it would cause a painful transition for relatively little gain, particularly as atoms at special positions can be detected in other ways anyway.

**Comment by merkys** [comment]
This convinces me. The issue can be closed.
