### ISSUE TITLE
cif_core.dic: some default enumeration values are given in DDL1, but not in DDLm

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#57]
When compared to the ``DDL1`` version of the dictionary the ``DDLm`` seems to be missing the following enumeration default values:

| ID  | Data name  | Default | 
|---|---|---|
| 1 | _space_group_symop_operation_xyz | x,y,z  |
| 2 | _space_group_symop_id  | 1  |
| 3 | _cell_angle\_(alpha\|beta\|gamma) | 90 |
| 4 | _cell_reciprocal_angle\_\(alpha\|beta\|gamma) | 90 |
| 5 | _refine_ls_extinction_method  | Zachariasen  |
| 6 | _geom_bond_multiplicity | 1 |
| 7 | _atom_site_constraints | . |
| 8 | _atom_site_calc_attached_atom | . |

I was wondering if these defaults were removed on purpose or unintentionally? The consensus on this issue would allow the appropriate modification of the legacy DDL1 dictionary as well.

My thoughts on the default values mentioned above (referred to by their table IDs): 

**1,2,3,4**
Was this removal carried out to accommodate the addition of  `triclinic` as the default value of the ``_space_group_crystal_system`` data item (as outlined in #58)?

I do imagine some situations where these defaults might lead to incorrect conclusions even though the CIF file itself is completely valid. I.e. modulated or magnetic structures use a different set of data items to provide the space group/symops thus resulting in a lack of the _space_group_symop data items. This in turn leads to interpreting the lack of '_space_group_symop' data items as a 'P 1' cell. Of course, one could always first check for the existence of those other data items before assuming the defaults, but this does require prior knowledge about the relationship between these data items.

Maybe the ``_enumeration.default`` definition in DDLm/DDL1 should be updated to reflect that, as in:
``The default value for the defined item if it is not specified explicitly and cannot be unambiguously extrapolated from other data items.``

**7,8**
It seems that these default values are overall correct since the lack of these data items imply that the related techniques were not applied thus resulting in a '.' (inapplicable) special value.

**Comment by jamesrhester** [comment]
I believe that the general trend is away from use of default values, as in practice the absence of a data name does not always mean that the default value is intended. I also agree with the updated definition for _enumeration.default, as it clarifies the precedence (i.e. attempt to deduce the value before applying the default).  In the case of DDLm the relationships are clear owing to the dREL methods, and these relationships are implicitly correct for the aliased DDL1 datanames as well.

**Comment by vaitkus** [comment]
I fully agree with the trend. The question, however, remains -- should these defaults be removed from the DDL1 legacy dictionaries as well?

**Comment by jamesrhester** [comment]
I think that they should be removed from the legacy dictionaries, and as there seem to be no other objections: @vaitkus,  please close this issue once you have done this.

**Comment by vaitkus** [comment]
Most of the default enumeration values have been removed from the core legacy dictionary. The publ_ related ones have been left intact to mirror the decisions made in the DDLm core dictionary.
