### ISSUE TITLE
cif_core.dic: restricting _diffrn_radiation_source (_diffrn_source) data item values to an enumerator set

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#59]
When compared to the ``DDL1`` version of the dictionary the ``DDLm`` seems to have restricted the ``_diffrn_radiation_source`` (``_diffrn_source``) data item values from a free-form text field to a set of 6 enumerators. However, it seems that the suggested enumerator values were not previously widely used. An inspection of 272032 CIF files from COD revision 202351 was carried out. After naively cleaning up the values (lowercasing, replacing white spaces with underscores, etc.) the following tables were compiled:

**Match against suggested values**

| Enumerator value  | Number of observations in the COD  |
|---|---|
| tube | 10 |
| nuclear | 0 |
| spallation | 15 |
| electro-micro | 0 |
| rot_anode | 0 |
| synch | 0 |

**20 most common values**

| Enumerator value | Number of observations in the COD  |
|---|---|
| fine-focus_sealed_tube | 199330 |
| sealed_tube | 9542 |
| rotating_anode | 9283 |
| enhance_(mo)_x-ray_source | 7333 |
| normal-focus_sealed_tube | 4797 |
| x-ray_tube | 3075 |
| supernova_(mo)_x-ray_source | 2710 |
| enraf_nonius_fr590 | 2147 |
| sealed_x-ray_tube | 2103 |
| supernova_(cu)_x-ray_source | 1920 |
| bruker-nonius_fr591_rotating_anode | 1826 |
| synchrotron | 1464 |
| rigaku_rotating_anode | 1165 |
| enhance_(cu)_x-ray_source | 1033 |
| fine-focus_sealed_x-ray_tube | 1022 |
| enhance_ultra_(cu)_x-ray_source | 985 |
| xray_tube | 899 |
| micro-focus_sealed_x-ray_tube | 633 |
| rotating_anode_x-ray_tube | 617 |
| fine-focus_rotating_anode | 592 |

In total, there were 1518 distinct values detected, but a more thorough canonicalization would surely reduce this number. As it can be seen, the top 20 observed values do fall into one of the suggested categories, although it should be discussed whether generalizing some of the sources as a single category does not obfuscate some important information (i.e. fine-focus_sealed_tube vs normal-focus_sealed_tube).

One dirty fix would be to move the current non-conforming ``_diffrn_source`` values to the already defined ``_diffrn_source.details``, but that would require the modification of multiple legacy CIFs. Furthermore, I am unsure how quickly the device/software manufacturers would react to the dictionary changes so non-valid CIFs are prone to propagate even further.

A more proper way to solve this might be to create a new data item (i.e ``_diffrn_source.class``) that would store the suggested enumeration values. The ``_diffrn_source`` data name then could be either declared as an alias of ``_diffrn_source.details`` or returned to the way it was defined in ``DDL1``. Of course, aliasing the item would raise the risk of these two data names clashing in already existing CIF files, but in actuality, the ``_diffrn_source.details`` has only been used 30 times in the entirety of the COD.

What do You think? I will attach the complete frequency table to this issue in case somebody is interested in analyzing it further ([COD-r202351-diffrn-source-types.txt](https://github.com/COMCIFS/cif_core/files/1418355/COD-r202351-diffrn-source-types.txt)).

**Comment by jamesrhester** [comment]
Thank you for the detailed information. I believe that `_diffrn_source.device` is the actual DDLm dataname aliased to `_diffrn_radiation_source`. However, it is clear that `_diffrn_source.device` cannot be aliased to `_diffrn_source` or `_diffrn_radiation_source` for the reasons you state.  Instead, the DDLm dictionary should define a dataname for legacy use, like `_diffrn_source.description`, which would be aliased to `_diffrn_radiation_source` and be deprecated.  This should involve no changes to DDL1.

**Comment by vaitkus** [comment]
Acknowledged.

**Comment by jamesrhester** [comment]
_diffrn_source.description has been aliased to _diffrn_source and the aliases removed from _diffrn_source.device.

**Comment by vaitkus** [comment]
The mentioned changes seem to have not been pushed to GitHub since the ``_diffrn_source.description`` data item is not defined and the ``_diffrn_source`` data item is still aliased to the ``_diffrn_source.device``. Or am I missing something?

**Comment by jamesrhester** [comment]
Sorry, my mistake, I had not performed the commit or pushed it. Should be OK now, see commit 1d22696

**Comment by vaitkus** [comment]
Thank You.
