### ISSUE TITLE
templ_enum.cif: the _element_symbol enumerator contains old names of elements 111 and 112

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#60]
The enumerator contains the unununium (Unn) and ununbium (Uub) which have now been officially renamed to roentgenium (Rg) and copernicium (Cn) accordingly. Since it is highly unlikely that any crystal structure so far has used the old names I would suggest simply replacing them.

In addition to that, element 110 is twice defined in the enumerator -- once as darmstadtium (Ds) and once using the old name ununnilium (Uun). The old name should probably be removed for the same reason Uun and Uub should not be added.

**Comment by jamesrhester** [comment]
I agree and will make these changes in the next commit.

**Comment by vaitkus** [comment]
Thank You for the correction.
