### ISSUE TITLE
cif_core.dic: enumerator list of the _exptl_crystal.colour_primary data item differs between DDL1 and DDLm versions 

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#61]
The issue is most similar to the one raised in #51, but it affects a different data item (_exptl_crystal.colour_primary data). I assume that the same solution (merging the value sets) should be applied here as well.

As far as the ``DDLm`` version is concerned it lacks 2 values when compared to the ``DDL1`` version -- `colourless` and `gray`.  The first one should probably be added to the enumerator with the appropriate RGB code of [`.`, `.`, `.`]; the second one already exists in the ``DDLm`` with a different spelling (``grey``) and should either be added as an alternative spelling or the value in the ``DDL1`` should be corrected appropriately.

What do You think?

**Comment by jamesrhester** [comment]
How often does 'gray' appear in the COD?  I would prefer only one spelling but this is an English/American variation.

**Comment by vaitkus** [comment]
According to COD revision 204214:

| Data name | Spelling  | Count | 
|---|---|---|
| _exptl_crystal_colour | grey | 588 |
| _exptl_crystal_colour | gray | 177 |
| _exptl_crystal_colour_primary | grey | 0 |
| _exptl_crystal_colour_primary | gray | 33 |

It seems that the usage of the *gray* spelling is not that numerous in the COD. I would say it is safe to outright replace the *gray* value in the DDL1. Do you agree?

Also, a somewhat related change should probably also be made. Currently, the DDLm ``templ_enum.cif`` spells the word "**grey**" consistently throughout the file (`grey`, `grey_light`, `grey_slate`, etc.). The only exception is the the `_exptl_crystal_colour_modifier` data item where the enumerator value "**grayish**" appears (as inherited from DDL1). I would suggest replacing this value in both the `DDL1` and the `DDLm` version of the dictionary to "**greyish**". Some statistics from the COD revision 204214:

| Data name | Spelling  | Count | 
|---|---|---|
| _exptl_crystal_colour | greyish | 4 |
| _exptl_crystal_colour | grayish | 47 |
| _exptl_crystal_colour_modifier | greyish | 0 |
| _exptl_crystal_colour_modifier | grayish | 39 |

**Comment by jamesrhester** [comment]
We should not render historical data files incorrect by excluding `gray` and `grayish`. So I will (with heavy heart) add it as an alternative spelling in `templ_enum.cif`, and add `greyish` as well.

**Comment by vaitkus** [comment]
Understood. Following that logic the ``\_exptl_crystal_appearance.hue`` should also contain the ``colourless`` enumerator value. The RGB code could potentially be given as ``[ . . . ]``.

On a general note, a bit of incompatibility between DDL1 and DDLm is allowed -- it is a major version revision after all.

**Comment by jamesrhester** [comment]
Added colourless in commit dfb3b36
