### ISSUE TITLE
cif_core.dic: data items refering to publication pages should not be restricted to integers

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#63]
Data items ``_citation.page_first``, ``_citation.page_last``, ``_journal.page_first`` and ``_journal.page_last``are currently defined as having the ``Index`` or ``Integer`` data types. However, in actuality the page index often consists not only of numbers, but also meaningful character prefixes/postfixes (i.e. the same issue of the journal might contain pages '10' and 'S10', the 'S' specifying it being a part of the supplementary material, etc.). I propose to change the data type to ``Text`` or ``Code``.

**Comment by jamesrhester** [comment]
I agree that `Code` is more appropriate.

**Comment by jamesrhester** [comment]
The next commit will include a fix for this. I chose 'Encode' as the purpose and 'Text' as the contents to avoid possible case-sensitivity issues.

**Comment by vaitkus** [comment]
Great, thank You.

I will close the issue since it is resolved.
