### ISSUE TITLE
cif_core.dic: some enumeration ranges differ between DDL1 and DDLm versions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#64]
The following enumeration ranges seem two have changed during the translation:

| ID  | Data name  | Value in DDL1 | Value in DDLm 
|---|---|---|---|
| 1.1 | _cell_length_a | 0.0:  | 1.: |
| 1.2 | _cell_length_b | 0.0:  | 1.: |
| 1.3 | _cell_length_c | 0.0:  | 1.: |
| 1.4 |  _diffrn_reflns_point_group_measured_fraction_max | 0:1.0 | 0.95:1.0 |
| 1.5 | _geom_bond_multiplicity | 0: | 1: |
| 1.6 |  _refine_ls_number_reflns | 0: | 1: |

1) The changes **1.1**, **1.2**, **1.3** seems to correspond to the dimensions of a hydrogen atom. If the change was intentional I will port it to the DDL1 version;
2) The **1.4** change seems strange since the new enumeration value corresponds to the enumeration value of the ``_diffrn_reflns_point_group_measured_fraction_full`` data item. Maybe a copying error is to blame for this change?
3) The new enumeration range in **1.5** conflicts with the current definition of the data item which states that "``in cases where the full list of bonds is given, one of the series of equivalent bonds may be assigned the appropriate multiplicity while the others are assigned a value of 0.``
4) It could be argued that the **1.6** was unnecessary since '0' could still be a valid value, but if this change was intentional I will port it to the DDL1 version;

**Comment by jamesrhester** [comment]
I agree with all your comments. I will instead correct the DDLm dictionary.

**Comment by vaitkus** [comment]
Understood. I have updated the DDL1 version accordingly.

**Comment by jamesrhester** [comment]
Will be fixed in latest commit.

**Comment by vaitkus** [comment]
Great, thank You for the correction.

Closing.
