### ISSUE TITLE
cif_core.dic: enumeration range of _citation.database_id_Medline data item was removed in the DDLm version

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#65]
During the transition from ``DDL1`` to ``DDLm`` the data type of ``_citation.database_id_Medline`` data item was changed from ``numb`` to ``Code`` and the enumeration value (1;+inf) was removed. Was this done purposely and should it be backported to the DDL1 version?

**Comment by jamesrhester** [comment]
As far as I can tell Medline IDs can now contain decimal points followed by digits to indicate version. Therefore this data type should simply be a Code and not an enumeration value. The DDL1 version should be changed accordingly.

**Comment by vaitkus** [comment]
Thank You for clearing that up. I have updated the DDL1 version accordingly.
