### ISSUE TITLE
templ_attr.cif: contradictory definition in the display_colour save block 

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#67]
The ``display_colour`` save block contains contradictory information. The enumeration range provided explicitly using the ``_enumeration.range`` ([``0``;``255``]) and the range imposed by the ``Index`` data type ([``1``; ``+inf``)) are in conflict. The data type should probably be changed to "``Integer``".

**Comment by jamesrhester** [comment]
I agree. I will update this in the next commit.

**Comment by vaitkus** [comment]
Thank You for the correction.
