### ISSUE TITLE
cif_core.dic: some data items would be better described using the "count" data type rather than the "index" data type

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#69]
Data items ``_refln.symmetry_epsilon``, ``_refln.symmetry_multiplicity``, ``_atom_site.site_symmetry_multiplicity``, ``_atom_site.site_symmetry_order``, ``_atom_type.electron_count``, ``_citation.journal_issue``, ``_citation.journal_volume``,
``_atom_type.atomic_number`` are declared as being of the 'Index' data type, but do not seem to describe data items that serve as indices. Of course, some of these data items, such as ``_atom_type.atomic_number`` or ``_citation.journal_volume`` could be used as indices in some situations, but the question then arises why the same 'Index' data type is not granted to similar data items like ``_space_group.IT_number`` or ``_journal.volume``. I would suggest redefining them as being of the "Count" data type and assigning the appropriate enumeration range.

**Comment by jamesrhester** [comment]
It seems that `Index` is being treated as the equivalent of a non-zero, non-negative integer as used in Fortran to index arrays. The name is probably unfortunate, as it is useful to have a shorthand way of expressing this common situation. I have no strong preference, but certainly 'Count' with an enumeration range of 1: is a synonym for 'Index' so there can't be a strong objection changing them. Is the main reason for suggesting this just the connotations of the word 'Index'?

**Comment by vaitkus** [comment]
You are totally correct about these two being interchangeable. The main reason was indeed the connotations behind both the word 'Index' (as something that is being used for indexing) and the word 'Count' (as something that is counted). However, I do admit that I might be splitting hairs with this suggestion if the data type simply refer only to the allowed values and do not carry any additional meaning.

**Comment by jamesrhester** [comment]
I will leave the current behaviour as is.
