### ISSUE TITLE
cif_core.dic: _citation_author.ordinal and _citation_editor.ordinal data items would be better defined as being of the 'index' data type

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#70]
Since the ``_citation_editor.ordinal`` and ``_citation_editor.ordinal`` data items declare the order of the citation authors/editors in the citation author/editor list it would make sense declaring them as being of the ``Index`` data type. Currently, the ``_citation_author.ordinal`` is declared as being of the ``Code`` type and  ``_citation_editor.ordinal`` of the ``Count`` type which seems a bit misleading. I understand the necessity of declaring data item ``_citation_author_citation_id`` as being of the ``Code`` type since values such as "primary" were previously permitted and even given as an example in the ``DDL``, but for the ``*.ordinal`` data items it is probably not required. The COD revision 202406 seems to contain only a single instance of the ``_citation_author_ordinal``data item and in the case mentioned it is used as an index.

**Comment by jamesrhester** [comment]
I agree that these should be changed to `Index`.

**Comment by jamesrhester** [comment]
Will be fixed in next commit

**Comment by vaitkus** [comment]
Great, thank You.

I will close the issue since it has been resolved.
