### ISSUE TITLE
cif_core.dic: proposal to make _atom_site.Wyckoff_symbol an enumerator

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#71]
The ``_atom_site.Wyckoff_symbol`` is currently allows any values fitting the Encode type format. A somewhat related data item ``_space_group_Wyckoff.letter``, however, is defined as a set of enumerator values. I propose moving the enumerator values into the ``templ_attr.cif`` file and declaring both data items as importing these enumerator values.

**Comment by jamesrhester** [comment]
I agree with this proposal and will implement it on a future commit.

**Comment by vaitkus** [comment]
Thank You.

**Comment by vaitkus** [comment]
@jamesrhester , maybe I could take a crack at this?
