### ISSUE TITLE
cif_core.dic: proposal to limit _space_group_Wyckoff.multiplicity data item values to 1:192

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#72]
Currently, the ``_space_group_Wyckoff.multiplicity`` allows any Integer value. A somewhat related ``_atom_site.site_symmetry_multiplicity`` data item, however, is defined as being limited to value 1:192. I propose updating the ``_space_group_Wyckoff.multiplicity`` definition in a similar fashion.

Alternatively, both definition could be update to provide an enumerator list of all possible multiplicities thus providing an even stricter check (disallowing '5', '7', etc.).

**Comment by jamesrhester** [comment]
I'm not sure how this value might change for incommensurate and magnetic structures.  I need to check this one with those groups.

**Comment by jamesrhester** [comment]
Upon reflection I think we can adopt this suggestion as any expansions to the meaning of Wyckoff multiplicity should simply define their own data name. The expectation of enough programmers will be that the maximum is 192 even if they don't read the dictionary. And nobody responded to my request for comment so it clearly isn't a big enough issue to worry about.

**Comment by vaitkus** [comment]
Would an enumeration range of [1:192] or an enumeration list be preferred?

**Comment by jamesrhester** [comment]
An enumeration range would be appropriate.
