### ISSUE TITLE
templ_enum.cif: differing spellings of the word "metre"

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#77]
The ``units_code`` save block in the ``templ_enum.cif`` contains two distinct spellings of the same word -- "metre" and "meter". The spelling should be canonicalized in all cases and related dictionaries should be updated.

**Comment by jamesrhester** [comment]
Agreed. I'll change throughout to 'metre', on the basis that we have to choose something.

**Comment by vaitkus** [comment]
Great, thank You.

**Comment by jamesrhester** [comment]
Fixed in latest commit
