### ISSUE TITLE
cif_core: incomplete _publ_manuscript_incl_extra.item data item definition

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#81]
The ``_publ_manuscript_incl_extra.item`` data item is defined as having the ``Link`` purpose (using the ``_type.purpose`` data item), however, the ``_name.linked_item_id`` data item is not provided in the definition data frame.

**Comment by vaitkus** [comment]
Understood.

**Comment by jamesrhester** [comment]
Fixed in latest commit
