### ISSUE TITLE
cif_core: incorrect item purpose of several data items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#82]
Several data items in the ``cif_core`` dictionary have their purpose incorrectly declared as ``Number`` instead of ``Measurand``. These data item have associated SU data items even though su values are not permitted for data items of the ``Number`` type. The following data items are affected:

- ``_diffrn.ambient_pressure`` (linked to by ``_diffrn.ambient_pressure_su``);
- ``_diffrn.ambient_temperature`` (linked to by ``_diffrn.ambient_temperature_su``);
- ``_chemical_conn_bond.distance`` (linked to by ``_chemical_conn_bond.distance_su``);
- ``_refine_diff.density_max`` (linked to by ``_refine_diff.density_max_su``);
- ``_refine_diff.density_min`` (linked to by ``_refine_diff.density_min_su``);
- ``_refine_diff.density_rms`` (linked to by ``_refine_diff.density_rms_su``).

There is also a somewhat related question. The use of su's is prohibited for data item with the ``Number`` purpose and is mandatory for data items with the ``Measurand`` purpose, however, it is not entirely clear if data items with other type of purpose are allowed to have standard uncertainties or is this feature strictly restricted to ``Measurand`?

**Comment by jamesrhester** [comment]
Good catch. Only 'Measurand' data names should have associated SU values. I will update the dictionary and close this when done.

**Comment by vaitkus** [comment]
Thank You for the clarification.

**Comment by vaitkus** [comment]
After having a second look at the dictionaries I have two additional comments:
1) The ``diffraction_radiation_wavelength.value`` data item has been assigned the 'Number' purpose in the DDLm dictionary and as such has been striped of the ability to have an associated s.u. value. However, in the DDL1 version of the dictionary the s.u. value is explicitly allowed. The data item
should probably be changed to 'Measurand' as well;
2) The existence of the ``_chemical_conn_bond.distance_su`` data item is actually quite strange. The 
``CHEMICAL_CONN_BOND`` category states that the associated data items describe a 2D chemical structure and are mainly used to reconstruct a 2D chemical diagram. As such, the bond distances are not really measured and probably should not contain standard uncertainties. Alternatively, the category itself could be redefined to refer to a 3D structure and actual measured bond distances, but the change should be properly described in the data item definitions.

**Comment by vaitkus** [comment]
Some of the data items have been accordingly updated in PR #117.

More comments are needed on the ``_diffrn_radiation_wavelength.value`` and ``_chemical_conn_bond.distance_su`` data items before proceeding further.

**Comment by jamesrhester** [comment]
Certainly `_diffrn_radiation_wavelength.value` should have an SU, and `_chemical_conn_bond.distance_su` should not exist.

**Comment by vaitkus** [comment]
Closing the issue since it has been resolved.
