### ISSUE TITLE
ddl.dic: overly restrictive _dictionary_valid loop values

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#83]
The _dictionary_valid loop is a great way of adding an extra level of validation, however, in a few cases they seem to be a bit too restrictive:

1. Data items from the IMPORT category are prohibited in the Category context, even though such imports are allowed in some cases (i.e. importing the entire dictionary into the HEAD category). On the other hand, there are no restrictions on the IMPORT category in the Dictionary context, even though this type of imports should probably not be allowed since we could end up with two HEAD categories or a tree of categories that is detached from the main hierarchy.
2. The ``_category.key_id`` and ``_category_key.name`` data items are recommended in the Category context, but they this only makes sense in the looped categories. I understand that there is probably no way to apply this recommendation only to the looped categories, but some kind of a comment denoting this situation would be useful.

**Comment by jamesrhester** [comment]
1. Agreed. The import items should only be possible at Category and Item level
2. As Set categories can be viewed as a single row Loop category, it is harmless to include `_category_key.name` in a Set definition. Additionally, as a Set category may become Looped in advanced applications, authors may consider it worthwhile creating the key data names ahead of time.  The appropriate place to comment on this is presumably in the entry for `_category_key.name`.

**Comment by vaitkus** [comment]
Understood, thank You for the clarification.

**Comment by jamesrhester** [comment]
Prohibition/allowance of import statements fixed in latest commit
