### ISSUE TITLE
Should the Cartesian-crystal axis transformation matrix be free choice?

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#85]
The data names given in the `_atom_sites_Cartn_transform` category include dREL expressions that produce a transformation matrix from crystal to orthogonal axes according to the Rollett convention (c parallel to z etc.). The dictionary suggests that this is a 'default' choice (see `_atom_sites_Cartn_transform.matrix` and the text 'the default choice...',) that is, it is possible for this matrix to be defined with Cartesian axes aligned differently. However, if this is the case the dREL code is not always correct, as dREL calculates axes according to the Rollett convention and will therefore give values that do not match a data file that has adopted a different convention.

I'm not sure if these data names can be explicitly restricted to the Rollett convention. I assume there are good reasons for an alternative Cartesian axis/crystal axis alignment.

As historical background, these data names existed in the DDL1 dictionary, but the dREL was inserted to explicitly calculate a matrix according to the Rollett convention so that dREL methods could explicltly work through to calculate the structure factor from the model.

**Comment by jamesrhester** [comment]
Solving this will require adding new data names under <code>atom_sites_Cartn_transform</code> describing the orientation of the crystal axes in terms of Cartesian components. The defaults would then be the Rollett convention, and we indeed specify these defaults. Normally we are not happy with defaults because they presume information that may actually have been different (e.g. temperature) and use of the wrong information would affect the science, but in this case the effect of a different axis choice will be easily detectable in later calculations.

**Comment by kkitahara5101** [comment]
How do you think if the _enumeration.default is set at the value according to the Rollett convention by using Definition method?

**Comment by jamesrhester** [comment]
Thanks for the suggestion @kkitahara5101 .

Just to expand on the idea I had above: there would be three new vector data names, named something like `_atom_sites_Cartn_transform.a_axis_Cartn`/`b_axis_Cartn`/`c_axis_Cartn`. These are of course just the columns (or is it rows? I forget) of `_atom_sites_Cartn_transform.matrix`, which could then be constructed using a normal 'Evaluation' method.

Now, just to make sure I understand @kkitahara5101 's suggestion: the problem with my suggestion is that the default Rollett convention requires mathematics to calculate some of these vectors in monoclinic and triclinic spacegroups. Such mathematics is only available in dREL methods.  An `Evaluation` method would calculate a value that is *always* true, but we only want a value that is calculated if nothing else is specified. So, because a `Definition` method is designed to add attribute values to a definition itself, it could be used to create a value for `_enumeration.default`.

Unfortunately as far as I can tell `Definition` methods were intended to create attributes at dictionary reading time, not at data file reading time. Therefore I think we might be forced to simply create a data name `_atom_site_Cartn_transform.convention` and provide `Rollett` as the default option. Then the `_atom_site_Cartn_transform.matrix` dREL could check the value for this option and create the 
transformation matrix accordingly.

**Comment by kkitahara5101** [comment]
Thanks for the reply.

I should note one thing regarding this issue.
If Definition methods are available only at dictionary reading time, some methods in cif_core dictionary, e.g. one in _refine_diff.density_max, do not work because they refer an instance value like `if (_diffrn_radiation.probe == "neutron")`.

https://github.com/COMCIFS/cif_core/blob/4b61be5136fa10c2f0d5a52e45b207181d05fcfd/cif_core.dic#L22322-L22351

**Comment by jamesrhester** [comment]
Yes, I think I was wrong and @kkitahara5101 is correct in  https://github.com/COMCIFS/cif_core/issues/85#issuecomment-512090859. This would be the cleanest solution I think.

**Comment by kkitahara5101** [comment]
Thanks for the reply @jamesrhester.
I like your solution, too. I just wanted to show another possibility, and by which, I wanted to understand the functionality of the Definition method more.

**Comment by jamesrhester** [comment]
The latest cif_core dictionary has changed the Cartesian transform matrix to use a ``Definition`` method to calculate the default setting. So if a matrix is not given explicitly, it will use the Rollett conventions.
