### ISSUE TITLE
cif_core.dic: the _geom_angle.atom_site_label_2 does not link to _atom_site.label

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#87]
The ``_geom_angle.atom_site_label_2`` does not link to the ``_atom_site.label`` even though the ``_geom_angle.atom_site_label_1`` and ``_geom_angle.atom_site_label_3`` data items do. I propose adding the ``_name.linked_item_id       '_atom_site.label'`` to its definition.

**Comment by jamesrhester** [comment]
I agree and have made this change in my local copy ready for upload after a few more changes.

**Comment by vaitkus** [comment]
Great, thank You.

**Comment by jamesrhester** [comment]
Fixed in latest commit
