### ISSUE TITLE
cif_core.dic: _space_group.name_H-M_alt and _space_group.name_H-M_full data items should be merged

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#89]
Currently, the ``_space_group.name_H-M_alt`` and ``_space_group.name_H-M_full`` data items are described in separate save frames with slightly differing descriptions, although, they seem to refer to the same thing.

I propose merging them into a single definition and retaining the data names as aliases.

**Comment by jamesrhester** [comment]
These items were inherited from the symmetry dictionary, which had the intention of capturing all the subtleties of symmetry descriptions. Presumably there was a perceived need to allow a free form H-M symbol (*_alt), as well as the formal short IT symbol (*_ref) and the full IT name (*_full). So I don't think we can touch them.

**Comment by vaitkus** [comment]
Acknowledged.
