### ISSUE TITLE
ddl.dic: some data names used in description text lack underscore prefixes

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#90]
In most cases the data item descriptions refer to other data items using their full data names, however, in several cases the underscore prefix was left out:

| Data item | Partial data name | Full data name |
|---|---|---|
| _category.key_id | category_key.name | _category_key.name |
| _category_key.name | category.key_id | _category.key_id |

I propose adding those prefixes to homogenise the notation.

**Comment by jamesrhester** [comment]
I agree.

**Comment by vaitkus** [comment]
Issue has been solved with pull #113.
