### ISSUE TITLE
cif_core.dic: some data names used in description text lack underscore prefixes

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#91]
In most cases the data item descriptions refer to other data items using their full data names, however, in several cases the underscore prefix was left out:

| Data item | Data name | Full data name |
|---|---|---|
| _exptl_crystal.density_meas_temp_gt | exptl_crystal.density_meas_temp | _exptl_crystal.density_meas_temp |
| _exptl_crystal.density_meas_temp_lt | exptl_crystal.density_meas_temp | _exptl_crystal.density_meas_temp |
| _atom_type.element_symbol | atom_type.symbol | _atom_type.symbol |
| _publ_manuscript.creation | publ_manuscript.processed | _publ_manuscript.processed |
| _valence_param.ref_id references | valence_ref.id | _valence_ref.id |

I propose adding those prefixes to homogenise the notation.

**Comment by jamesrhester** [comment]
I agree

**Comment by vaitkus** [comment]
Issue has been solved with pull #113.
