### ISSUE TITLE
cif_core: space group related data items reference undefined data items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#93]
It seems, that during the migration from DDL1 to DDLm some of the definitions
from the symmetry dictionary got merged into the core dictionary. However,
some inconsistencies in regards to the data item descriptions have arisen
from these actions. Namely, the descriptions of the data items were left
intact while some of the data items were not ported:

| Data item | Referenced data item |
| - | - |
| _space_group.IT_coordinate_system_code | \_space_group.transform_* |
| _space_group.name_H-M_full | _space_group.reference_setting |
| _space_group.name_H-M_ref  | _space_group.reference_setting |

Maybe these data item were accidentally left out?

**Comment by jamesrhester** [comment]
Some data names were postponed to a separate extension dictionary where multiple space groups could be described and the transformations between them captured.  Edited definitions in the next commit will remove references to these data names.

**Comment by vaitkus** [comment]
Thank You for the clarification. I will close the issue since it has been resolved.
