### ISSUE TITLE
cif_core: some data items reference undefined data items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#94]
The descriptions of some of the data items contain references to data items/
categories that do not seem to be defined in the dictionary:

| Data item | Referenced data item |
|-|-|
| _exptl_crystal.description | exptl_crystal_size |
| _audit.schema | _audit_conform.dictionary |

**Comment by jamesrhester** [comment]
Will be fixed in next commit

**Comment by vaitkus** [comment]
Great, thank You.

I will close the issue since it has been resolved.
