### ISSUE TITLE
cif_core: incorrect description of the _exptl.transmission_factor_min data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#96]
The description of the `_exptl.transmission_factor_min` data item incorrectly references the `_exptl_absorpt.correction_T_max` data item instead of `_exptl_absorpt.correction_T_min`.

For comparison, the `_exptl.transmission_factor_max` data item correctly references the `_exptl_absorpt.correction_T_max` data item.

**Comment by jamesrhester** [comment]
Will be fixed in next commit.

**Comment by vaitkus** [comment]
Great, thank You.

Closing.
