### ISSUE TITLE
cif_core: homogenize the notation of symop examples in data item descriptions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#97]
The `_space_group_symop.id` and the `site_symmetry` save frame (in `templ_attr.cif`) describe the symmetry operations as being of the form '**n_klm**', however, some of the functions (`_function.SymEquiv`, `_function.SymKey`, `_function.SymLat`, `_function.Symop`, `_function.Symop`, `_function.SymLat` ) describe the symops as being of the form '**n_pqr**'. I propose that one of these notations be chosen and used throughout the dictionary to clearly denote that they are referring to the same thing.

**Comment by jamesrhester** [comment]
This should be changed to `n_pqr` throughout to avoid confusion with use of `hkl` for Miller indices.

**Comment by vaitkus** [comment]
Issue has been solved with pull #113.
