### ISSUE TITLE
cif_core: remove the '@' notation from the data item descriptions

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#98]
Several data item descriptions contain atom names prefixed with the '**@**' symbol. Since this notation is neither explained nor widely used I propose removing it all-together and referring to the data items and categories by their names as it is done through-out the dictionary.

The table below provides the locations of the '@' data names and their propose
replacements:

| Data item | Prefixed name | Name replacement |
|-|-|-|
| _reflns.Friedel_coverage | @diffrn_refln_ | DIFFRN_REFLN |
| _reflns.Friedel_coverage | @reflns_Friedel_coverage | _reflns.Friedel_coverage |
| _refine_ls.wR_factor_gt  | @reflns_threshold_expression | _reflns.threshold_expression |

**Comment by jamesrhester** [comment]
Strange. These should definitely be removed.

**Comment by vaitkus** [comment]
Issue has been solved with pull #113.
